### ISSUE TITLE
Default RTSP Video Not Displaying

### ISSUE THREAD

**Issue by dlmutiny** [shbatm/MMM-RTSPStream#1]
EDIT: Added version number

I haven't been able to get the video to display on the MagicMirror. Everything appears to have installed correctly. No errors during the install process. I tested the feed using the VLC process outlined in the README. Feed played just fine. The MagicMirror log shows a constant "Waiting for connections..".

mm-out-0.log output
`Starting MagicMirror: v2.1.1
Loading config ...
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: MMM-RTSPStream
All module helpers loaded.
Starting server on port 8080 ...
Starting server op port 8080 ...
Server started ...
Connecting socket for: MMM-RTSPStream
Sockets connected & modules started ...
Launching application.
Starting WebSocket server on port 9999. Waiting for connections...
`

config.js 
`{
            module: 'MMM-RTSPStream',
            postion: 'middle_center',
            config: {
                autoStart: true,
                rotateStreams: false,
                rotateStreamTimeout: 10,
                showSnapWhenPaused: false,
                moduleWidth: 354,
                moduleHeight: 240,
                stream1: {
                    name: 'BBB Test',
                    url: 'rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov',
                    snapshotUrl: '',
                    snapshotRefresh: 10, // Seconds
                    frameRate: "30",
                    port: 9999,
                }
            }
        },
`

**Comment by shbatm** [comment]
@dlmutiny - There was a typo in the example config -- please correct `postion` to `position` and let me know if you're able to see the sample stream.  I have fixed this in the README.

**Comment by dlmutiny** [comment]
Jeez, I totally overlooked that. Thanks, problem solved. Works great.
