### ISSUE TITLE
After the update the module does not work

### ISSUE THREAD

**Issue by JVF2** [shbatm/MMM-RTSPStream#101]
After the update, the module no longer starts.
Even if I set in the "config.js" the setting to factory defaults.

Any idea?

Many thanks in advance.

**Comment by JVF2** [comment]
<img width="1280" alt="log" src="https://user-images.githubusercontent.com/74675605/194329642-1a318b5e-7f8b-4efa-95ae-6ce34577fcd9.png">

**Comment by shbatm** [comment]
What version of the core are you running?
Did you re-run `npm install` inside the module folder after updating?

I am not seeing the error on a Raspberry CM4, MM 2.21.0.

**Comment by shbatm** [comment]
I reverted the `node-fetch` back to v2.x instead of the newest v3.x. Try removing your `/modules/MMM-RTSPStream/node_modules` folder and re-running `npm install`.

**Comment by JVF2** [comment]
I am working with a Raspberry Pi 4 and version 2.21.0 of the MagicMirror.
After your update everything works perfectly now.
Thank you.
