### ISSUE TITLE
Typing Error

### ISSUE THREAD

**Issue by mrdago** [shbatm/MMM-RTSPStream#17]
@shbatm - Hi, great modul! I'm testing your modul with a ctronics camera and it is working fine with omxplayer. Using the JSMpeg player causes an issue as there is a typing error in the port assignment in line 359 of MMM-RTSPstream (ffpmegPort --> ffmpegPort).
````
359    var sUrl = `ws://${document.location.hostname}:${this.config[stream].ffpmegPort}`;
````

**Comment by shbatm** [comment]
Fixed. Please re-pull the module.  Thank you for catching this!

```shell
cd ~/MagicMirror/modules/MMM-RTSPStream
git pull
```
