### ISSUE TITLE
RTSP Feed not working 

### ISSUE THREAD

**Issue by langonej** [shbatm/MMM-RTSPStream#19]
Using an amcrest based setup. RTSP URL works fine in VLC. Module configuration generated via the http server using the bunny.mov file works great. Using omxplayer local on a rasp pi 3. 

However when I swap out the bunny mov RTSP URL for my camera’s RTSP it doesn’t work. I get a blank screen. Same config with bunny url works fine 
I’ve tried both tcp and udp

I’ve tried hardcoding frame rates. Nothing works. Any ideas? Dying to get this to work.

**Comment by shbatm** [comment]
Please share your config and camera model and I'll take a look.

Also, please confirm if there's any console errors being spit out.

**Comment by langonej** [comment]
Stand down.  I cleaned up code in my MMM-HFIO (unrelated module) and it's now working.  My HFIO module is a home automation and I wonder if I had an unclosed tag somewhere.

THANK YOU!

**Comment by shbatm** [comment]
Ok Great! I'm glad you got it working. Let me know if you have any more questions.

P.S. I removed your password from the config above.
