### ISSUE TITLE
Grey screen

### ISSUE THREAD

**Issue by glelan** [shbatm/MMM-RTSPStream#2]
Hello
I have try your module and it's working with Big Bunny stream. but when I change the URL to my local IP cam : rtsp://192.168.0.100:554/onvif1
then I get just a grey square where I should have the video.
the URL is working well with VLC from my Iphone and laptop.
any idea ?
I'm using a SRICAM SP009
thanks

**Comment by shbatm** [comment]
A few things to try:

- Do you need a username/password? If so, add it to the url: `rtsp://<user>:<pass?@192.168.0.100:554/onvif1`

From a command line, please try:
`ffmpeg -rtsp_transport tcp -r 30 -i rtsp://192.168.0.100:554/onvif1 -f mpegts -codec:v mpeg1video -bf 0 -` and see if there are any errors.  You can also add `hideFfmpegOutput: false` to the `stream1` section in the module config and check MM logs instead.

If not working, try `-rtsp_transport udp` in the line above.  (if that works, change `tcp` to `udp` in Line 14 of `modules/MMM-RTSPStream/node_modules/node-rtsp-stream-es6/src/mpeg1muxer.js`)

**Comment by glelan** [comment]
tcp--> udp was the trick ;-) thanks a lot !!

**Comment by shbatm** [comment]
@glelan - Great! I'm glad it was an easy fix.  Just to let you know, I've updated the module to add a `protocol: "tcp"` or `protocol: "udp"` option in the stream config.  If you want to update and try it:
```shell
cd ~/MagicMirror/modules/MMM-RTSPStream
git pull
npm run-script update
```

**Comment by glelan** [comment]
Now it's working but mpc is not playing sound while the rtsp stream is on. If i put pause and then run mpc i get my music and i need to put play on rtsp stream to have both.
Do you have an idea?
Thanks


Grégoire Le Lan
