### ISSUE TITLE
HIKVISION cam not working?

### ISSUE THREAD

**Issue by appletowr** [shbatm/MMM-RTSPStream#20]
Hi,

Just installed this module for MM2 to view an RTSP stream from my Hikvision IP camera (DS-2CD2185FWD-I). I use the following config:

                {
                        module: "MMM-RTSPStream",
                        position: "top_center",
                        header: "Voordeur",
                        config: {
                                        autoStart: true,
                                        rotateStreams: false,
                                        rotateStreamTimeout: 10,
                                        moduleWidth: 640,
                                        moduleHeight: 480,
                                        localPlayer: 'omxplayer',
                                        stream1: {
                                                               name: 'Voordeur',
                                                               url: 'rtsp://username:passwd@192.168.1.217:554/Streaming/Channels/101/',
//                                                               url: 'rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov',
                                                               snapshotType: '',
                                                               snapshotRefresh: 10,
                                                               width: 640,
                                                               height: 480,
                                                               framerate: "30",
                                                 },
                                }
                },

When starting MM2 I get the following output for the IP cam:

Starting stream stream1 with args: [
    "--avdict",
    "rtsp_transport:tcp",
    "--win",
    "608, 107, 1248, 587",
    "--live",
    "--video_queue",
    "4",
    "--fps",
    "30",
    "rtsp://192.168.1.217:554/Streaming/Channels/101/"
]
PM2: omx_stream1 already running. Stopping old instance...
Starting PM2 for omx_stream1
PM2 started for omx_stream1

In MM2 I see the placeholder, but the screen is black. When using the demo URL, everything works fine. Also in VNC Viewer both demo URL as well as my own URL work fine.

Can you please help me in setting this up correctly? 

Patrick

**Comment by shbatm** [comment]
I will look closer later but 2 things to try:

Try streaming the low res channel first, change the very end of the url to a 2 from 1.

Try this url after the port number (w 2 /s) 
:554//Streaming/Channels/1

The latter is what I use for my Hikvision cameras

**Comment by shbatm** [comment]
@appletowr Were you ever able to get this working?

**Comment by appletowr** [comment]
Yes, I was. thanks for your help. That helped.
