### ISSUE TITLE
MMM-RTSPStream only displays a Loading message

### ISSUE THREAD

**Issue by johnnyswindle** [shbatm/MMM-RTSPStream#21]
MM starts and I only get a Loading message for RTSPStream.  This is what is displaying in the terminal:
`Whoops! There was an uncaught exception...
TypeError: `port` or a `server` must be provided
    at new WebSocketServer (/home/pi/MagicMirror/modules/MMM-RTSPStream/node_modules/node-rtsp-stream-es6/node_modules/ws/lib/WebSocketServer.js:44:11)
    at VideoStream.startListener (/home/pi/MagicMirror/modules/MMM-RTSPStream/node_modules/node-rtsp-stream-es6/src/videoStream.js:32:24)
    at Class.startListener (/home/pi/MagicMirror/modules/MMM-RTSPStream/node_helper.js:49:32)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-RTSPStream/node_helper.js:257:22)
    at Socket. (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:513:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

My config was generated by the web interface and is as follows:
`   {
	    module: "MMM-RTSPStream",
	    position: "bottom_right",
	    config: {
	        autoStart: true,
	        rotateStreams: true,
	        rotateStreamTimeout: 30,
	        moduleWidth: 354,
	        moduleHeight: 240,
	        localPlayer: 'omxplayer',
	        remotePlayer: 'ffmpeg',
	        showSnapWhenPaused: false,
	        remoteSnaps: false,
	        stream1: {
	            name: 'Front Door',
	            url: 'rtsp://Administrator:Password@192.168.0.31:88/videoSub',
	            frameRate: 'undefined',
	            width: undefined,
	            height: undefined,
	            },
	        }
		},`

I can play the stream via VLC without any issue.  Not sure where or how to correct the error.

Thanks....

**Comment by johnnyswindle** [comment]
I also tested with the default video stream.....I get a blank square.

`
{
    module: "MMM-RTSPStream",
    position: "bottom_right",
    config: {
        autoStart: true,
        rotateStreams: false,
        rotateStreamTimeout: 10,
        moduleWidth: 354,
        moduleHeight: 240,
        localPlayer: 'omxplayer',
        remotePlayer: 'ffmpeg',
        showSnapWhenPaused: false,
        remoteSnaps: false,
        stream1: {
            name: 'Test',
            url: 'rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov',
            frameRate: 'undefined',
            width: undefined,
            height: undefined,
            },
        }
},
	
`

**Comment by shervin422** [comment]
I also have this issue :(

Any assistance would be greatly appreciated.

**Comment by shbatm** [comment]
You have remote playback enabled without specifying a web socket port for it. Please try the following and let me know if it works:

Option 1: Disable remote playback by changing `remotePlayer: 'ffmpeg'`, to `remotePlayer: 'none'`.

Option 2: If you need remote playback (ability to view the stream on a screen not directly attached to the RPi), add a `ffmpegPort: 9999` (or some other random port) to your stream config.

**Comment by johnnyswindle** [comment]
Thank you for the advice.  Option 1 worked.  Now I just need to figure out how to align the image inside the box. Do I use moduleOffset or absPosition?  If moduleOffset is used, to move it right is the number postive or negative?  If moduleOffset is used, to move down is it a positive or negative?

To use absPosition will be a big challenge.

Thanks for your patience and for this module

![20180425_210839](https://user-images.githubusercontent.com/225859/39282409-eca73198-48ce-11e8-8479-de86cb143db0.jpg)

**Comment by shbatm** [comment]
For moduleOffset, down and right are positive (IIRC). You can use either; absPosition works better if you have other modules that change size and it's moving the video window or if you use `zoom` on your mirror config which causes confusion between coordinate systems. 

For absPosition, look at your MM log and it should spit out the the position omxplayer is drawing the video, use that as your starting point and adjust from there.
