### ISSUE TITLE
Header and Cameraframe Alignment

### ISSUE THREAD

**Issue by dersch81** [shbatm/MMM-RTSPStream#23]
Hi, the Module works quite good with rotating  snapshots of 5 cams on a Pi2. But there is a mismatch of the alignment of the header line and cameraframe. The camerapicture and frame is matching very good in automode. But how can I align the header and frame?
![20180618_225435](https://user-images.githubusercontent.com/13754891/41654086-94e8c80a-7488-11e8-9722-8d31c459bec6.jpg)

**Comment by shbatm** [comment]
Please try to add the following to your `~/MagicMirror/css/custom.css` file. 

```css
.MMM-RTSPStream .innerWrapper {
  margin: 0px;
}
```

**Comment by dersch81** [comment]
Hmm it doesn't change it, that's how i modifed the file. Is it correct?

` body {
.MMM-RTSPStream .innerWrapper {
  margin: 0px;
}
 }
`

**Comment by dersch81** [comment]
OK my bad,  that is working:

`/*****************************************************
 * Magic Mirror                                      *
 * Custom CSS                                        *
 *                                                   *
 * By Michael Teeuw http://michaelteeuw.nl           *
 * MIT Licensed.                                     *
 *                                                   *
 * Add any custom CSS below.                         *
 * Changes to this files will be ignored by GIT. *
 *****************************************************/

body {
  /* only things you want to change on the 'body' element (eg: background: red;) */
}

.MMM-RTSPStream .innerWrapper {
  margin: 0px;
}`
