### ISSUE TITLE
How to hide the stream?

### ISSUE THREAD

**Issue by IwanZh** [shbatm/MMM-RTSPStream#25]
I was using Google Assistant to display content on Magic Mirror, the question is how to hide / show RTSP stream ? I have other contents to show beside CCTV streams.

**Comment by shbatm** [comment]
@IwanZh -- There are several other modules that allow you to hide/show modules--MMM-RTSPStream should respond to them assuming they send the normal module show and hide requests. Here's a few to look at:
[MMM-Carousel](https://github.com/shbatm/MMM-Carousel)
[MMM-RemoteControl](https://github.com/Jopyth/MMM-Remote-Control)
[MMM-ModuleScheduler](https://github.com/ianperrin/MMM-ModuleScheduler)
[MMM-ProfileSwitcher](https://github.com/tosti007/MMM-ProfileSwitcher)

**Comment by IwanZh** [comment]
Thank's for quick response, I will look it up further.
