### ISSUE TITLE
Loading MMM-RTSPStream

### ISSUE THREAD

**Issue by aro28** [shbatm/MMM-RTSPStream#26]
Hi all,
Please help me with below issue. Module is not showing a live RTSP video stream on my MM.
I can see just black screen.. 
![screenshot from 2018-08-05 23-38-08](https://user-images.githubusercontent.com/25077676/43688348-bb265a2e-9908-11e8-9920-09489277fc6d.png)

**Comment by aro28** [comment]
Config file is below:
{
    module: "MMM-RTSPStream",
    position: "middle_center",
    config: {
        autoStart: true,
        rotateStreams: true,
        rotateStreamTimeout: 10,
        moduleWidth: 354,
        moduleHeight: 240,
        localPlayer: 'omxplayerg',
        stream1: {
            name: '',
            frameRate: '25',
            hdUrl: 'rtsp://admin:123@172.20.20.5/h264Preview_01_main',
            snapshotType: 'url',
            snapshotRefresh: 10,
            width: 528,
            height: 360,
	    port: 9999,
            },
        }
},

**Comment by aro28** [comment]
{
    module: "MMM-RTSPStream",
    position: "middle_center",
    config: {
        autoStart: true,
        moduleWidth: 354,
        moduleHeight: 240,
//        localPlayer: 'omxplayerg',
    localPlayer: 'ffmpeg',   
        stream1: {
            name: '',
            frameRate: '25',
            url: 'rtsp://admin:admin@172.20.20.5/h264Preview_01_main',
            snapshotRefresh: 10,
            snapshotUrl: '',
	    width: 528,
            height: 360,
	    port: 9999,
            },
        }
},

**Comment by shbatm** [comment]
Please try first:

localPlayer: 'omxplayerg', should not have a 'g' on the end.
Stream Name cannot be blank:  name: "stream 1", will work.

Please try these things first, if it is still not working, please check web
browser console (via Ctrl+shift+I) and command line (or Pm2 log) for errors
and share those here.

**Comment by aro28** [comment]
pi@mymirror:~ $ pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/home/pi/.pm2/pm2.log last 15 lines:
PM2        | 2018-08-06 00:09:18: Time                 : Mon Aug 06 2018 00:09:18 GMT+0600 (+06)
PM2        | 2018-08-06 00:09:18: PM2 version          : 2.9.1
PM2        | 2018-08-06 00:09:18: Node.js version      : 6.14.2
PM2        | 2018-08-06 00:09:18: Current arch         : arm
PM2        | 2018-08-06 00:09:18: PM2 home             : /home/pi/.pm2
PM2        | 2018-08-06 00:09:18: PM2 PID file         : /home/pi/.pm2/pm2.pid
PM2        | 2018-08-06 00:09:18: RPC socket file      : /home/pi/.pm2/rpc.sock
PM2        | 2018-08-06 00:09:18: BUS socket file      : /home/pi/.pm2/pub.sock
PM2        | 2018-08-06 00:09:18: Application log path : /home/pi/.pm2/logs
PM2        | 2018-08-06 00:09:18: Process dump file    : /home/pi/.pm2/dump.pm2
PM2        | 2018-08-06 00:09:18: Concurrent actions   : 2
PM2        | 2018-08-06 00:09:18: SIGTERM timeout      : 1600
PM2        | 2018-08-06 00:09:18: ===============================================================================
PM2        | 2018-08-06 00:09:19: Starting execution sequence in -fork mode- for app name:mm id:0
PM2        | 2018-08-06 00:09:19: App name:mm id:0 online

/home/pi/.pm2/logs/mm-error-0.log last 15 lines:
0|mm       | libGL error: MESA-LOADER: failed to retrieve device information
0|mm       | MESA-LOADER: failed to retrieve device information
0|mm       | MESA-LOADER: failed to retrieve device information
0|mm       | ERROR! Could not find main module js file for MMM-googlemaps
0|mm       | TypeError: `port` or a `server` must be provided
0|mm       |     at new WebSocketServer (/home/pi/MagicMirror/modules/MMM-RTSPStream/node_modules/node-rtsp-stream-es6/node_modules/ws/lib/WebSocketServer.js:44:11)
0|mm       |     at VideoStream.startListener (/home/pi/MagicMirror/modules/MMM-RTSPStream/node_modules/node-rtsp-stream-es6/src/videoStream.js:32:24)
0|mm       |     at Class.startListener (/home/pi/MagicMirror/modules/MMM-RTSPStream/node_helper.js:49:32)
0|mm       |     at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-RTSPStream/node_helper.js:257:22)
0|mm       |     at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11)
0|mm       |     at emitTwo (events.js:106:13)
0|mm       |     at Socket.emit (events.js:191:7)
0|mm       |     at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:513:12
0|mm       |     at _combinedTickCallback (internal/process/next_tick.js:67:7)
0|mm       |     at process._tickCallback (internal/process/next_tick.js:98:9)

/home/pi/.pm2/logs/mm-out-0.log last 15 lines:
0|mm       | Connecting socket for: newsfeed
0|mm       | Starting module: newsfeed
0|mm       | Sockets connected & modules started ...
0|mm       | Launching application.
0|mm       | Create new news fetcher for url: http://static.feed.rbc.ru/rbc/logical/footer/news.rss - Interval: 300000
0|mm       | Starting WebSocket server on port undefined. Waiting for connections...
0|mm       | Whoops! There was an uncaught exception...
0|mm       | MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm       | If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|mm       | Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/prostotak1981%40gmail.com/public/basic.ics - Interval: 1000
0|mm       | GET_WUNDERGROUND
0|mm       | Create new news fetcher for url: http://www.googlehomecommands.net/rss.php?category=8 - Interval: 300000
0|mm       | Use existing news fetcher for url: http://static.feed.rbc.ru/rbc/logical/footer/news.rss
0|mm       | GET_WUNDERGROUND
0|mm       | Use existing news fetcher for url: http://www.googlehomecommands.net/rss.php?category=8

**Comment by aro28** [comment]
localPlayer: 'ffmpeg', 
        stream1: {
            name: 'stream 1',
            frameRate: '25',
            url: 'rtsp://admin:ibijhimg@172.20.20.5/h264Preview_01_main',
            snapshotRefresh: 10,
            snapshotUrl: '',
            width: 528,
            height: 360,
            port: 9999,
            },
        }
},

**Comment by aro28** [comment]
It is still not working, what can i do else?

**Comment by aro28** [comment]
![screenshot from 2018-08-06 00-35-57](https://user-images.githubusercontent.com/25077676/43688747-b813ee02-9910-11e8-847d-ea2e28093fec.png)

**Comment by aro28** [comment]
Resolved. I disabled GL driver and it fixed.

**Comment by shbatm** [comment]
Glad you got it working. If you use ffmpeg version for any reason, port
should be ffmpegPort

Also, I always recommend using the web config generator (see Readme)

**Comment by aro28** [comment]
Yes. I used web conf. Thanks!
Another question. 
Currently, "MMM-RTSPStream" module is overlapping my another module "MMM-WunderGround" which is located on top right position.
Where can i change margins for that module?
Thanks advance!
