### ISSUE TITLE
BigBuckBunny Test Stream 

### ISSUE THREAD

**Issue by goprojojo** [shbatm/MMM-RTSPStream#28]
I have MMM-RTSPStream working with my IP camera. However this BigBuckBunny Test Stream is also showing in my screen. So now I have 2 streams which is not defined in my config.js. How can I remove this BigBuckBunny Test Stream? See attached image.

>                 {
>                         module: "MMM-RTSPStream",
>                         position: "middle_center",
>                         header: "CAMERA",
>                         config: {
>                         autoStart: true,
>                         rotateStreams: false,
>                         rotateStreamTimeout: 10,
>                         moduleWidth: 800,
>                         moduleHeight: 480,
>                         moduleOffset: -5,
>                         localPlayer: 'omxplayer',
>                         remotePlayer: 'none',
>                         showSnapWhenPaused: true,
>                         remoteSnaps: true,
>                         stream2: {
>                         name: 'Cam',
>                         url: 'rtsp://user:password@123.456.789:10/Streaming/Channels/2',
>                         frameRate: '20',
>                         hdUrl: 'rtsp://user:password@123.456.789:10/Streaming/Channels/1',
>                         snapshotUrl: 'rtsp://user:password@123.456.789:10/Streaming/Channels/2/picture',
>                         snapshotType: 'url',
>                         snapshotRefresh: 10,
>                         width: 800,
>                         height: 480,
>             }
>         }
> },
>

![image](https://user-images.githubusercontent.com/14301878/46254714-a6a70380-c493-11e8-8df3-0fb7c0e0fd6a.png)

**Comment by shbatm** [comment]
Have you tried completely restarting everything including the RPi? If it's
still happening try `pm2 status` and see if there are more than one
`omxstream` instances running. You can reset Pm2 with `pm2 kill` and then
restart the mirror.

**Comment by shbatm** [comment]
`Pm2 kill` at the command should wipe out all of your pm2 instances. Then
restart.

**Comment by goprojojo** [comment]
After pm2 kill and sudo reboot the two streams streams still showing. I also tried the following:
pm2 status
pm2 show omx_stream1 (which shows the details of BigBunny Test stream)
pm2 delete omx_stream1 (to delete the stream)
pm2 restart mm

Now the omx_stream1 is gone but still see the borders of the deleted stream

Then sudo reboot
After restarting the mirror both the streams showing again 🙈

I need to permanently delete the unwanted stream but don't know how...

**Comment by shbatm** [comment]
Please double check you don't accidentally have 2 copies of the module in
your config. The only place it could be coming from is the config, so you
may have a errant section (either stream or a full copy of the module
config) floating around.

**Comment by goprojojo** [comment]
Ok you were right. There was another instance floating around. I deleted this and after reboot I was able to see the right stream. Thnx!
