### ISSUE TITLE
RTSP Stream Blank, Test Link Audio Only

### ISSUE THREAD

**Issue by tempUser99** [shbatm/MMM-RTSPStream#29]
RSTP stream video does not appears however the testing link does play audio with no video.

{
                        module: "MMM-RTSPStream",
                        position: "bottom_right",
                        header: "Attached Garage",
                        config: {
                                autoStart: true,
                                rotateStreams: true,
                                rotateStreamTimeout: 5,
                                moduleWidth: 354,
                                moduleHeight: 240,
                                localPlayer: 'omxplayer',
                                remotePlayer: 'none',
                                showSnapWhenPaused: false,
                                remoteSnaps: true,
                                stream1: {
                                        name: '1',
                                        url: 'rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov',
                                        frameRate: 'undefined',
                                        width: undefined,
                                        height: undefined,
                                }
                                stream2: {
                                        name: '2',
                                        url: 'rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov',
                                        frameRate: 'undefined',
                                        width: undefined,
                                        height: undefined,
                                }
                        }
                }

**Comment by tempUser99** [comment]
Commands have been executed:

cd ~/MagicMirror/modules/MMM-RTSPStream
npm install

**Comment by shbatm** [comment]
Please confirm: you are testing on a Raspberry Pi and using a monitor
connected directly to the Pi (not VNC or a web browser).

**Comment by tempUser99** [comment]
Confirmed.

Running on Raspberry Pi 3B+ connected directly to HDMI monitor.

After continuing to debug the following information was found:

1) When encountering the issue with only audio playing and not video (just black box with white border) the RaspberryPi was set up to use "GL (Full KMS) OpenGL desktop driver with full KMS".

2) When changing to "GL (Fake KMS) OpenGL desktop driver with fake KMS" omxplayer appears to fail completely without playing video or audio at all.

3) When changing to "Legacy Original non-GL desktop driver" the video will play when using omxplayer directly but still does not run when used while using MagicMirror. This seems like the most viable option as omxplayer will run the stream when wall directly in terminal. Also the following screenshot shows what `pm2 status` looks like.

<img width="588" alt="screen shot 2018-10-02 at 9 48 53 am" src="https://user-images.githubusercontent.com/43507929/46356544-91afa900-c628-11e8-8acf-95b576812854.png">

After seeing this I ran `pm2 start omx_stream1` and the video appeared. When MagicMirror is rebooted the same issue is seen with omx_stream1 sitting "stopped".

**Comment by shayfer** [comment]
tempuser99,

I am running into the same issue that you were having. Are you saying the solution was to use the legacy video driver? I am using the Open GL per the setup options on the Magic Mirror Configuring the Raspberry Pi. Are you able to also rotate the screen using the Legacy Original?

Thanks!

**Comment by tempUser99** [comment]
shayfer,

Yes I am able to rotate using the Legacy driver. That is the best solution I have found to this point.

I am now, however, having persistent issues with disconnect. Eventually (within about 24 hours) I loose all streams connection when I am not rotating. The `omg_stream1` will still be online but the stream is blank on the screen.

I am not sure if this is due to this issue or another.

**Comment by shbatm** [comment]
I've experienced the dropout issue with OMX Player also. I'm not sure what causes it (its something to do with OMXPlayer itself, not the module.  I created a workaround to restart the PM2 `omx_streamX` instances every X hours.  Please try switching to the `wip_omxrestart` branch, adding `omxRestart: 24` to your stream configuration and test.  This should restart the OMX Stream every 24 hours.

**Comment by shayfer** [comment]
shbatm,

Thanks I added that!  

tempUser99 I am guessing you simply went into raspi-config and selected Original Legacy non-gl. I still can't get video. I can get it by following in the directions where I save a stream as a strm and play it in VLC. What model camera are you using? I am using Foscam.

**Comment by shbatm** [comment]
Something else to try: in `raspi-config` try increasing the memory split
and giving the GPU more memory.

**Comment by tempUser99** [comment]
Good point there shbatm. I am actually using `512` for my gpu memory.

**Comment by shayfer** [comment]
Great help guys thanks!  I increased to 512 as well. I also matched usertemp99's settings the exact pretty much. I am looking at it from VNC but at least I have a box with a Pause Icon. When I get home I will see what is on the actual mirror TV. I also noticed using the Legacy has made the resolution alot smaller. I will have to play with that if the stream works.

Thanks!

**Comment by shbatm** [comment]
Ah, that might be it. Omxplayer outputs straight to hmdi. If you're trying
to view on VNC you won't see anything unless you're using ffmpeg.

**Comment by shayfer** [comment]
Unfortunately still a blank image. I increased to 512, changed to Legacy, and match userTemp99's config file.  Of course adding my own IP and credentials.  In VLC my stream for my Foscam FI982 works great using this format rtsp://administrator:passwordetc@192.168.1.78/videoMain. I am making progress though since I know do see in PM a omx_stream1 listed.  Not sure what is left to try except maybe different stream addresses?  Thanks for both ya'll help!

![image](https://user-images.githubusercontent.com/25122376/46897867-e46c3a80-ce4a-11e8-9e95-30f90b28d36f.png)

**Comment by shayfer** [comment]
Good call. Yes, I am physically looking at the TV and the video is not playing with that URL.  So I have a fresh copy of Raspian and followed all the Magic Mirror steps with your configs. What should I try next?

**Comment by shayfer** [comment]
Is there a log file associated with this module by chance? I looked around but didn't see one. I did also try dropping the framerate to 10, plugging in the Pi to the LAN to eliminate something with wireless, and also tried connecting to a webcam that is hardwired as well.

**Comment by shbatm** [comment]
@shayfer It dumps everything to the MM console (if using PM2 you can watch it with `pm2 log mm` or access it in ~/.pm2/logs

The majority of the problems I see with this module comes from Omxplayer itself. If you can get omxplayer to play the stream from the command line, then you should be able to get the module to work. 

See the tail end of this forum thread for command line options. 

https://forum.magicmirror.builders/topic/2743/mmm-rtspstream-video-streaming-from-live-feeds-security-cameras/10

@tempUser99 did you get everything working?

**Comment by shayfer** [comment]
shbatman & tempUser99,

Just a follow-up and in case anyone sees this. I re-imaged the pie and used the legacy driver per tempuser99. I also changed the gpu memory to 256. I was able to successfully play the test stream. I then proceeded to finally figure out to use this in omxplayer to see my webcam stream. omxplayer --avdict rtsp_transport:udp rtsp://administrator:********@192.168.1.75:554/videoMain. (Using udp seemed to fix it) It is slow and takes forever to load but I did see it. I want to test with it hardwired this week and not through wireless. (I am using a Linksys EA8500 with line of sight about 20 feet.) Using the legacy driver I noticed my resolution is not as good as using the OpenGL. I need to play with the resolution I guess to see if I can match it up. I.E. I can load 10 modules with space to spare and the legacy it is all smashed together. 

Thanks for all your great help and insight!

**Comment by shayfer** [comment]
The most I could get out was a single frame, sometimes from a camera. I ordered a different kind of camera from Amazon. I think those Foscams are trash. Or at least the model I got. (I will admit they do work great with ISpy but that is it.)

**Comment by shayfer** [comment]
Update: Ordering an AXIS camera fixed my problem of no video! I can confirm that Foscam is trash when it comes to rtsp streams to the Mirror. At least that particular model. How can I make the image line up with the box though?

Thanks!

![unnamed](https://user-images.githubusercontent.com/25122376/49324072-1feec100-f4ec-11e8-9747-808770931b54.jpg)

**Comment by tempUser99** [comment]
Good work on that. I was worried Foscam would be the issue. I have been experiencing major instability as well with the RTSP stream and Foscam. Good to know another brand looks like it is working better.

What you are looking for is the `moduleOffset` settings. I think it is exactly what you need.

**Comment by shbatm** [comment]
@tempUser99 and @shayfer -- Do you both have everything working?

Just to let you know I pushed several updates to the `develop` branch that addresses some of the instability issues with omxplayer not starting/stopping when it should, and also added a VLC option for using the new version of Raspbian which has HW accelerated VLC included by default.

I did also confirm that the OpenGL driver (fake KMS and real) doesn't play well with omxplayer on the new version of Raspbian--you'll have to use VLC if you upgrade and still want the Fake KMS driver enabled.

Thanks!

**Comment by shayfer** [comment]
@shbatm  Yes everything is still working great for me! I did see where it said I was XX amount of commits behind for rtsp and when I updated it I am still working fine.  I actually have been using the legacy driver since I wanted to use this module https://github.com/rejas/MMM-MotionDetector  

I see now that module above supports OpenGL but I am worried to change since everything seems to be working great still.

*Not to hijack this comment but in regards to the above module do ya'll have experience coding modules? I am so close to modifying that module but I am missing something in the code. I'd like it to show the mirror when motion is detected. Problem is that module is to turn OFF the signal and I have a TCL TV that shows a RED no image signal that won't go away unless it gets another signal. Message me if ya'll could offer some help I'd appreciate!

Thanks!

Shayfer

**Comment by shbatm** [comment]
@shayfer glad it's working (and I didn't break anything else yet).

Probably better to get more help in the forum, but my 2 cents for the motion detection would be to replace [line 60](https://github.com/rejas/MMM-MotionDetector/blob/58dca47e371eb5108b089aefad84c7f74649d176/MMM-MotionDetector.js#L60) and [line 67](https://github.com/rejas/MMM-MotionDetector/blob/58dca47e371eb5108b089aefad84c7f74649d176/MMM-MotionDetector.js#L67) with sendNotification calls (not socket) and then use another module like MMM-Remote-Control or MMM-HideAll? to show and hide all modules instead of turning off the monitor.

**Comment by shayfer** [comment]
@shbatm I tried to message you without polluting up this thread but see it's not possible. I was wanting to try to pick your brain a little more on the above question if possible?
Thanks!
Shayfer
