### ISSUE TITLE
RTSPStream and music background

### ISSUE THREAD

**Issue by glelan** [shbatm/MMM-RTSPStream#3]
Hello
I'm using MPC and MPD as music client/server to have webradio on my mirror. If I have a live stream on your module playing and then run MPC to play a webradio URL, MPC is playing but there is no sound.
If I stop MPC, then pause the stream from your module and re run MPC then I get sound, I can also  play the RTSPStream once the radio is playing.

Do you have any idea why there is no sound ? My wife want to have the radio and I would like to have the RTSPStream ... so today I have radio and no rtspstream as it block the radio ;-)

Thanks for your help

**Comment by shbatm** [comment]
@glelan Unfortunately I don't have any way to test this.  My best guess is `ffmpeg` from this module is interfering with the instance running in MPD. I'm not sure exactly why though. When I get some time I will play around, for now you can try to narrow it down to `ffmpeg` by:
1. Disable MMM-RTSPStream in you MM2 config and run MPC/MPD web radio as you have been.  
2. From a command line, execute the following and see if the audio stops while this is streaming:
```shell
ffmpeg -rtsp_transport tcp -r 30 -i rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov -f mpegts -codec:v mpeg1video -bf 0 -
```
3. Out of curiosity, please also try:
```shell
ffmpeg -rtsp_transport tcp -r 30 -i rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov -f mpegts -codec:v mpeg1video -an -bf 0 -
```
