### ISSUE TITLE
RSTP stream is blank when enable GL driver (Full KMS)

### ISSUE THREAD

**Issue by aro28** [shbatm/MMM-RTSPStream#31]
Hi Shbatm!
RSTP stream is blank when enable GL driver (Full KMS).
Any ideas? Can it work with GL driver?
Thanks!

**Comment by shbatm** [comment]
This would be an issue with OMXPLAYER the underlying video player. I haven't played with the GL driver options enough to know how to make it work. If someone else has more background on omxplayer I'll take the help.

**Comment by shbatm** [comment]
Confirmed--this is an issue with OMXPlayer and the OpenGL driver being incompatible. Cannot fix this issue here.  I am working on a VLC version of the module which will allow you to use the OpenGL driver.
