### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by anthony6608** [shbatm/MMM-RTSPStream#32]
Hello,

Thank you very much for this module! I was hoping something like this existed as I want to add my front door camera to my MagicMirror! I followed all instructions however I cant get video to display.

My camera model is: Dahua IPC-HDW4431C-A-V2 IP Camera.
Usually I have the resolution on the camera set to 2592x1520 but changed it to 1080p just in case that was the issue but still no go.

I have followed everything step by step, using FFMPEG on the rpi i was able to connect and create a thumb.png file.

I've also done the following but no go:

Confirm you're looking at the actual display connected to the Pi, not over VLC.
Check the PM2 log for errors--(use pm2 log mm from ssh to stream the log or look in ~/.pm2/logs/)
change frameRate: 'undefined' to frameRate: undefined.
Try Channel 2 on the camera (lower res) and see if that works. Sometimes OMX chokes on the high-res (change the 1 to a 2 at the end of the url).
Try increasing the GPU memory split in raspi-config
Make sure the Pi is connecting to the camera correctly--set autoStart: false and add snapshotUrl: 'http://XXXX:XXXXXX@192.168.0.40:80//Streaming/Channels/2/picture', below the url.

Below is the config file. I am running the latest Raspbian on Rpi3 w/ the latest version of MM2. Please forgive me if i forgot anything.

  modules: [
                        {
                         module: "MMM-RTSPStream",
                         position: "middle_center",
                         header: "LIVE FEED",
                         config: {
                         autoStart: true,
                         rotateStreams: true,
                         rotateStreamTimeout: 20,
                         moduleWidth: 354,
                         moduleHeight: 240,
                         localPlayer: 'omxplayer',
                         remotePlayer: 'none',
                         showSnapWhenPaused: false,
                         remoteSnaps: true,
                         stream1: {
                         name: 'ENTRANCE',
                         url: 'rtsp://admin:XXXXXX@192.168.0.6:554/cam/realmonitor?channel=1&subtype=1',
//                       autoStart: false,
//                       snapshotUrl: 'rtsp://admin:XXXXXX@192.168.0.6:554/cam/realmonitor?channel=1&subtype=1', 
                         frameRate: undefined,
                         hdUrl: 'rtsp://admin:XXXXXX@192.168.0.6:554/cam/realmonitor?channel=1&subtype=1',
                         width: undefined,
                         height: undefined,
                                        }
                                }
                        },

**Comment by anthony6608** [comment]
Also, I am able to connect fine via VLC to the camera.

**Comment by shbatm** [comment]
I broke something in one of the last updates, so it may be the module. See this post for info:
https://forum.magicmirror.builders/topic/2743/mmm-rtspstream-video-streaming-from-live-feeds-security-cameras/163

You can try reverting (see instructions a couple comments up on that thread) or if you want to be a Guinea Pig, you can try the VLC version I'm working on...

**Comment by anthony6608** [comment]
Hey,

thanks for the quick response and yes, moments before I read your reply here I found the forum post. You know what I realized after taking a break from it and researching further. Although I followed the README to install I don't see a omx_stream1 │ 1 │ N/A │ fork │ online │ 6 │ 0% │ 2.8 MB │ in my pm2 list. The only thing I see is my magic mirror instance. Did I miss something during the install? Also I assume my cameras are supported right? And can I leave it at the highest resolution? Thanks.

**Comment by anthony6608** [comment]
Another thing in case i forgot to mention it. I do not have an omxplayer instance running when i pm2 list. I see quite a few people have pasted their output and seem to have this in their list. Did I miss a step somewhere? I will try to find instructions on how to revert and see what happens in the meanwhile. Thanks!

This is my pm2 list output:

│ App name    │ id │ version │ mode │ pid │ status │ restart │ uptime │ cpu │ mem      │ user │ watching │
├─────────────┼────┼─────────┼──────┼─────┼────────┼─────────┼────────┼─────┼──────────┼──────┼──────────┤
│ MagicMirror │ 0  │ 2.6.0   │ fork │ 916 │ online │ 0       │ 22m    │ 0%  │ 2.5 MB   │ pi   │ enabled  │
└─────────────┴────┴─────────┴──────┴─────┴────────┴─────────┴────────┴─────┴──────────┴──────┴──────────┘

**Comment by anthony6608** [comment]
**Ok, so I followed your steps on the forum to try out the VLC player route. Initially my RPI locked up during install:**

pi@raspberrypi:~ $ cd MagicMirror/
pi@raspberrypi:~/MagicMirror $ ls
CHANGELOG.md  config  css            fonts         index.html  js             LICENSE.md  module-types.ts  package.json       README.md     serveronly    tests         vendor
clientonly    core    dangerfile.js  Gruntfile.js  installers  jsconfig.json  modules     node_modules     package-lock.json  run-start.sh  splashscreen  translations
pi@raspberrypi:~/MagicMirror $     cd ~/MagicMirror
pi@raspberrypi:~/MagicMirror $ sed -i 's/electron": "\^2\.0\..*",/electron": "^3.0.13",/g' package.json
pi@raspberrypi:~/MagicMirror $ nmp install
-bash: nmp: command not found
pi@raspberrypi:~/MagicMirror $ npm install

> electron@3.0.13 postinstall /home/pi/MagicMirror/node_modules/electron
> node install.js

Downloading tmp-1358-1-SHASUMS256.txt-3.0.13
[============================================>] 100.0% of 4.79 kB (4.79 kB/s)
[            ......] \ postinstall: sill lifecycle electron@3.0.13~postinstall: Returned: code: 0  signal: null
[            ......] \ postinstall: sill lifecycle electron@3.0.13~postinstall: Returned: code: 0  signal: null
[            ......] \ postinstall: sill lifecycle electron@3.0.13~postinstall: Returned: code: 0  signal: null
[            ......] \ postinstall: sill lifecycle electron@3.0.13~postinstall: Returned: code: 0  signal: null
[            ......] \ postinstall: sill lifecycle electron@3.0.13~postinstall: Returned: code: 0  signal: null
^C^C^C^C^C
^Z
^Z
^C
^C

**I then rebooted and proceeded to rerun the following and it said finished successfully and usually my magic mirror would auto start on reboot but now its just going to the desktop? Can you help me fix this? Im new to all of this so not sure whats going on.** 

**_I pasted pm2 logs below as well._**

Last login: Thu Jan  3 12:58:56 2019
pi@raspberrypi:~ $ cd ~/MagicMirror/
pi@raspberrypi:~/MagicMirror $ ls
CHANGELOG.md  config  css            fonts         index.html  js             LICENSE.md  module-types.ts  package.json       README.md     serveronly    tests         vendor
clientonly    core    dangerfile.js  Gruntfile.js  installers  jsconfig.json  modules     node_modules     package-lock.json  run-start.sh  splashscreen  translations
pi@raspberrypi:~/MagicMirror $ sed -i 's/electron": "\^2\.0\..*",/electron": "^3.0.13",/g' package.json
pi@raspberrypi:~/MagicMirror $ npm install

> magicmirror@2.6.0 install /home/pi/MagicMirror
> cd vendor && npm install

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

audited 220 packages in 20.096s
found 3 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

> magicmirror@2.6.0 postinstall /home/pi/MagicMirror
> sh installers/postinstall/postinstall.sh && npm run install-fonts

MagicMirror installation successful!

> magicmirror@2.6.0 install-fonts /home/pi/MagicMirror
> cd fonts && npm install

audited 1 package in 2.851s
found 0 vulnerabilities

npm WARN grunt-stylelint@0.10.1 requires a peer of stylelint@^9.0.0 but none is installed. You must install peer dependencies yourself.

audited 2473 packages in 120.111s
found 9 vulnerabilities (7 low, 1 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
pi@raspberrypi:~/MagicMirror $ pm2 list
┌─────────────┬────┬─────────┬──────┬──────┬────────┬─────────┬────────┬─────┬──────────┬──────┬──────────┐
│ App name    │ id │ version │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem      │ user │ watching │
├─────────────┼────┼─────────┼──────┼──────┼────────┼─────────┼────────┼─────┼──────────┼──────┼──────────┤
│ MagicMirror │ 0  │ 2.6.0   │ fork │ 3714 │ online │ 107     │ 2s     │ 0%  │ 2.5 MB   │ pi   │ enabled  │
└─────────────┴────┴─────────┴──────┴──────┴────────┴─────────┴────────┴─────┴──────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
pi@raspberrypi:~/MagicMirror $ sudo reboot
Connection to 192.168.0.26 closed by remote host.
Connection to 192.168.0.26 closed.
Anthonys-Mac-Pro:Desktop tonyc$ ssh pi@192.168.0.26
pi@192.168.0.26's password: 
Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu Jan  3 13:26:14 2019
pi@raspberrypi:~ $ pm2 list
┌─────────────┬────┬─────────┬──────┬──────┬────────┬─────────┬────────┬─────┬──────────┬──────┬──────────┐
│ App name    │ id │ version │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem      │ user │ watching │
├─────────────┼────┼─────────┼──────┼──────┼────────┼─────────┼────────┼─────┼──────────┼──────┼──────────┤
│ MagicMirror │ 0  │ 2.6.0   │ fork │ 1359 │ online │ 19      │ 1s     │ 0%  │ 2.5 MB   │ pi   │ enabled  │
└─────────────┴────┴─────────┴──────┴──────┴────────┴─────────┴────────┴─────┴──────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
pi@raspberrypi:~ $ cd MagicMirror/
pi@raspberrypi:~/MagicMirror $ DISPLAY=:0 npm start

> magicmirror@2.6.0 start /home/pi/MagicMirror
> sh run-start.sh

pi@raspberrypi:~/MagicMirror $ pm2 list
┌─────────────┬────┬─────────┬──────┬──────┬────────┬─────────┬────────┬─────┬──────────┬──────┬──────────┐
│ App name    │ id │ version │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem      │ user │ watching │
├─────────────┼────┼─────────┼──────┼──────┼────────┼─────────┼────────┼─────┼──────────┼──────┼──────────┤
│ MagicMirror │ 0  │ 2.6.0   │ fork │ 2652 │ online │ 72      │ 1s     │ 0%  │ 2.6 MB   │ pi   │ enabled  │
└─────────────┴────┴─────────┴──────┴──────┴────────┴─────────┴────────┴─────┴──────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
pi@raspberrypi:~/MagicMirror $ 


**_PM2 LOGS_**

pi@raspberrypi:~/MagicMirror $ pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/home/pi/.pm2/pm2.log last 15 lines:
PM2        | 2019-01-03T13:31:05: PM2 log: App [MagicMirror:0] exited with code [0] via signal [SIGINT]
PM2        | 2019-01-03T13:31:05: PM2 log: App [MagicMirror:0] starting in -fork mode-
PM2        | 2019-01-03T13:31:05: PM2 log: App [MagicMirror:0] online
PM2        | 2019-01-03T13:31:07: PM2 log: App [MagicMirror:0] exited with code [0] via signal [SIGINT]
PM2        | 2019-01-03T13:31:07: PM2 log: App [MagicMirror:0] starting in -fork mode-
PM2        | 2019-01-03T13:31:07: PM2 log: App [MagicMirror:0] online
PM2        | 2019-01-03T13:31:08: PM2 log: App [MagicMirror:0] exited with code [0] via signal [SIGINT]
PM2        | 2019-01-03T13:31:08: PM2 log: App [MagicMirror:0] starting in -fork mode-
PM2        | 2019-01-03T13:31:09: PM2 log: App [MagicMirror:0] online
PM2        | 2019-01-03T13:31:10: PM2 log: App [MagicMirror:0] exited with code [0] via signal [SIGINT]
PM2        | 2019-01-03T13:31:10: PM2 log: App [MagicMirror:0] starting in -fork mode-
PM2        | 2019-01-03T13:31:10: PM2 log: App [MagicMirror:0] online
PM2        | 2019-01-03T13:31:12: PM2 log: App [MagicMirror:0] exited with code [0] via signal [SIGINT]
PM2        | 2019-01-03T13:31:12: PM2 log: App [MagicMirror:0] starting in -fork mode-
PM2        | 2019-01-03T13:31:12: PM2 log: App [MagicMirror:0] online

/home/pi/.pm2/logs/MagicMirror-error.log last 15 lines:
0|MagicMir | MESA-LOADER: failed to retrieve device information
0|MagicMir | [1597:0103/122232.835704:FATAL:bus.cc(1152)] D-Bus connection was disconnected. Aborting.
0|MagicMir | libGL error: MESA-LOADER: failed to retrieve device information
0|MagicMir | MESA-LOADER: failed to retrieve device information
0|MagicMir | MESA-LOADER: failed to retrieve device information
0|MagicMir | libGL error: MESA-LOADER: failed to retrieve device information
0|MagicMir | MESA-LOADER: failed to retrieve device information
0|MagicMir | MESA-LOADER: failed to retrieve device information
0|MagicMir | [957:0103/125530.085991:FATAL:bus.cc(1152)] D-Bus connection was disconnected. Aborting.
0|MagicMir | libGL error: MESA-LOADER: failed to retrieve device information
0|MagicMir | MESA-LOADER: failed to retrieve device information
0|MagicMir | MESA-LOADER: failed to retrieve device information
0|MagicMir | libGL error: MESA-LOADER: failed to retrieve device information
0|MagicMir | MESA-LOADER: failed to retrieve device information
0|MagicMir | MESA-LOADER: failed to retrieve device information

/home/pi/.pm2/logs/MagicMirror-out.log last 15 lines:
0|MagicMir | > magicmirror@2.6.0 start /home/pi/MagicMirror
0|MagicMir | > sh run-start.sh
0|MagicMir | 
0|MagicMir | 
0|MagicMir | > magicmirror@2.6.0 start /home/pi/MagicMirror
0|MagicMir | > sh run-start.sh
0|MagicMir | 
0|MagicMir | 
0|MagicMir | > magicmirror@2.6.0 start /home/pi/MagicMirror
0|MagicMir | > sh run-start.sh
0|MagicMir | 
0|MagicMir | 
0|MagicMir | > magicmirror@2.6.0 start /home/pi/MagicMirror
0|MagicMir | > sh run-start.sh
0|MagicMir | 

0|MagicMirror  | > magicmirror@2.6.0 start /home/pi/MagicMirror
0|MagicMirror  | > sh run-start.sh
PM2            | App [MagicMirror:0] exited with code [0] via signal [SIGINT]
PM2            | App [MagicMirror:0] starting in -fork mode-
PM2            | App [MagicMirror:0] online
0|MagicMirror  | > magicmirror@2.6.0 start /home/pi/MagicMirror
0|MagicMirror  | > sh run-start.sh
PM2            | App [MagicMirror:0] exited with code [0] via signal [SIGINT]
PM2            | App [MagicMirror:0] starting in -fork mode-
PM2            | App [MagicMirror:0] online
0|MagicMirror  | > magicmirror@2.6.0 start /home/pi/MagicMirror
0|MagicMirror  | > sh run-start.sh
PM2            | App [MagicMirror:0] exited with code [0] via signal [SIGINT]
PM2            | App [MagicMirror:0] starting in -fork mode-
PM2            | App [MagicMirror:0] online
0|MagicMirror  | > magicmirror@2.6.0 start /home/pi/MagicMirror
0|MagicMirror  | > sh run-start.sh
PM2            | App [MagicMirror:0] exited with code [0] via signal [SIGINT]
PM2            | App [MagicMirror:0] starting in -fork mode-
PM2            | App [MagicMirror:0] online
0|MagicMirror  | > magicmirror@2.6.0 start /home/pi/MagicMirror
0|MagicMirror  | > sh run-start.sh
PM2            | App [MagicMirror:0] exited with code [0] via signal [SIGINT]
PM2            | App [MagicMirror:0] starting in -fork mode-
PM2            | App [MagicMirror:0] online
0|MagicMirror  | > magicmirror@2.6.0 start /home/pi/MagicMirror
0|MagicMirror  | > sh run-start.sh
PM2            | App [MagicMirror:0] exited with code [0] via signal [SIGINT]
PM2            | App [MagicMirror:0] starting in -fork mode-
PM2            | App [MagicMirror:0] online
^C
pi@raspberrypi:~/MagicMirror $

**Comment by anthony6608** [comment]
Ugh, this is a headache. I had everything running except for RTSP and now nothing works, lol :(

Im sorry about the back to back posts, just want to make sure youre aware of everything to avoid back and forth. So, yesterday my pm2 list showed that I had mm and magicmirror running and my RPI was crashing etc, so i deleted and stopped mm and everything seemed to run smoother with just the MagicMirror instance running. I moved the mm startup script to ~/old_mm.sh. Before killing this mm process, I also noticed when I minimized to desktop I had 2 browser windows opened running MagicMirror (2 seperate instances it seems). I opened an issue on Mich's github and he said the the two instances are normal as usually one is just a startup script however it did seem like I was running two identical instances as I mentioned my Rpi kept locking up. Im not sure if thats relative to this but everything was working fine up until I executed the commands to update to VLC from your forum post. Now pm2 list shows MagicMirror online but it simply wont startup on the display. Here's the latest logs, I tried reinstalling electron but still no go. Again, sorry for the mess of replies. Just want to make sure you have all the info possible to make it easier. And thank you again for all of your help!

i@raspberrypi:~/MagicMirror $ pm2 logs MagicMirror
[TAILING] Tailing last 15 lines for [MagicMirror] process (change the value with --lines option)
/home/pi/.pm2/logs/MagicMirror-error.log last 15 lines:
0|MagicMir | MESA-LOADER: failed to retrieve device information
0|MagicMir | [1597:0103/122232.835704:FATAL:bus.cc(1152)] D-Bus connection was disconnected. Aborting.
0|MagicMir | libGL error: MESA-LOADER: failed to retrieve device information
0|MagicMir | MESA-LOADER: failed to retrieve device information
0|MagicMir | MESA-LOADER: failed to retrieve device information
0|MagicMir | libGL error: MESA-LOADER: failed to retrieve device information
0|MagicMir | MESA-LOADER: failed to retrieve device information
0|MagicMir | MESA-LOADER: failed to retrieve device information
0|MagicMir | [957:0103/125530.085991:FATAL:bus.cc(1152)] D-Bus connection was disconnected. Aborting.
0|MagicMir | libGL error: MESA-LOADER: failed to retrieve device information
0|MagicMir | MESA-LOADER: failed to retrieve device information
0|MagicMir | MESA-LOADER: failed to retrieve device information
0|MagicMir | libGL error: MESA-LOADER: failed to retrieve device information
0|MagicMir | MESA-LOADER: failed to retrieve device information
0|MagicMir | MESA-LOADER: failed to retrieve device information

/home/pi/.pm2/logs/MagicMirror-out.log last 15 lines:
0|MagicMir | > magicmirror@2.6.0 start /home/pi/MagicMirror
0|MagicMir | > sh run-start.sh
0|MagicMir | 
0|MagicMir | 
0|MagicMir | > magicmirror@2.6.0 start /home/pi/MagicMirror
0|MagicMir | > sh run-start.sh
0|MagicMir | 
0|MagicMir | 
0|MagicMir | > magicmirror@2.6.0 start /home/pi/MagicMirror
0|MagicMir | > sh run-start.sh
0|MagicMir | 
0|MagicMir | 
0|MagicMir | > magicmirror@2.6.0 start /home/pi/MagicMirror
0|MagicMir | > sh run-start.sh
0|MagicMir | 

0|MagicMirror  | > magicmirror@2.6.0 start /home/pi/MagicMirror
0|MagicMirror  | > sh run-start.sh
0|MagicMirror  | > magicmirror@2.6.0 start /home/pi/MagicMirror
0|MagicMirror  | > sh run-start.sh
0|MagicMirror  | > magicmirror@2.6.0 start /home/pi/MagicMirror
0|MagicMirror  | > sh run-start.sh
0|MagicMirror  | > magicmirror@2.6.0 start /home/pi/MagicMirror
0|MagicMirror  | > sh run-start.sh
^C
pi@raspberrypi:~/MagicMirror $ sh run-start.sh ^C
pi@raspberrypi:~/MagicMirror $ cd ..
pi@raspberrypi:~ $ sh run-^C
pi@raspberrypi:~ $ cd MagicMirror/

**Comment by shbatm** [comment]
Just confirming from [this forum post](https://forum.magicmirror.builders/topic/2743/mmm-rtspstream-video-streaming-from-live-feeds-security-cameras/164) -- everything is fixed now?

**Comment by anthony6608** [comment]
Well, I ended up just dumping that install and installing a fresh copy of Raspbian. I added 3-4 posts on the forum as I am still having trouble sing the VLC route with placement, other modules disabling video feed, video feed overlaying other modules no matter what settings. I will close this out for now, please check forum when you have a chance.

Also, I have removed all other modules and just trying to get RTSP sorted. Now that all modules are removed I am able to get a good stream BUT no matter what I do I have a black space on the right side so it doesn’t look clean at all.

When I remove ALL other modules it aligns in the box however it doesnt take up the full box its like showing half of the picture.

When I enable the maps module the feed is there but just a black box.

When I have commute module loaded it overlaps the module on the screen.

No matter how much I play with height/width settings, I cannot get it centered (right side always has black space) and cant get anything sized up correctly.
