### ISSUE TITLE
[Bug] FFMPeg stuck on loading. 

### ISSUE THREAD

**Issue by BKeyport** [shbatm/MMM-RTSPStream#34]
I'm unable to get this module to load and run with FFMPeg anymore - as of 3PM 1/4/19 (Pacific Time (Seattle)) 

Update was applied as of that time. 

I don't know how to retrieve logs. 

Configuration: 
		{
			module: "MMM-RTSPStream",
			position: "bottom_right",
			config: {
				autoStart: true,
				rotateStreams: false,
				rotateStreamTimeout: 10,
				moduleWidth: 370,
				moduleHeight: 245,
				localPlayer: 'ffmpeg',
				remotePlayer: 'none',
				showSnapWhenPaused: false,
				remoteSnaps: false,
				stream1: {
					name: 'Front Camera',
					url: 'rtsp://user:pass@FrontCam/h264Preview_01_sub', 
				ffmpegPort: 9999,
				shutdownDelay: 10000,
				hideFfmpegOutput: true,
				},
			}
		},

I do have some custom CSS in play in my mirror to maximize space: 

 body {
  margin: 4px;
  height: calc(100vh - 10px);
  width: calc(100vw - 5px);
}
.MMM-RTSPStream .innerWrapper {
  border: 0;
}

**Comment by shbatm** [comment]
Please try and reinstall the streaming module: run `npm i github:shbatm/node-rtsp-stream-es6` inside the MMM-RTSPStream folder

**Comment by BKeyport** [comment]
No Go. stuck on "Loading"

**Comment by BKeyport** [comment]
Figured out logs: 

TypeError: this.streams[name].startListener is not a function
    at Class.startListener (/home/pi/MagicMirror/modules/MMM-RTSPStream/node_he$
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-RTSPS$
    at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helpe$
    at emitTwo (events.js:126:13)
    at Socket.emit (events.js:214:7)
    at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:513:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by shbatm** [comment]
Ok, sorry, you'll have to switch to the `develop` branch or try deleting line 23 (`this.streams[name].startListener();`) in `node_helper.js`.  I fixed that error in the `develop` branch but it's buried in a commit with a bunch of other changes so I can't move it over to `master` just yet.

**Comment by BKeyport** [comment]
OK, switching to develop worked.

**Comment by shbatm** [comment]
Ok good. Once I confirm all the other bugs are fixed I'll merge develop back into the master.

**Comment by BKeyport** [comment]
Just as a note, I've switched back to OMXPlayer - and now restart my Mirror that runs that every 3 hours. Seems to prove to be more stable, and smoother, not jumpy as it was with ffmpeg.  Tried VLC, but it didn't work at all.

**Comment by BKeyport** [comment]
ahh, I started doing the restart for the stream only through cron and pm2, but I'll add this, why spew things all over the place.
