### ISSUE TITLE
MagicMirror freezing, error logs show RTSP errors.

### ISSUE THREAD

**Issue by anthony6608** [shbatm/MMM-RTSPStream#36]
Hi guys,

So i recently switched back to oxmplayer on my Rpi3 running latest Raspbian Stretch w/ desktop. I left it to run since yesterday and came back to see that MM2 is frozen. I can't still access the Rpi via ssh so its not completely locked up. Below (last log) is after I tried restarting MagicMirror with 
 'pm2 MagicMirror restart' the mirror is still stuck and not closing/re-opening. Stream is also frozen from last night. Any idea what is causing this?

**Uptime is:** 
 16:34:22 up 1 day,  3:12,  3 users,  load average: 3.48, 3.05, 2.88

**Error Logs:**

```
pi@raspberrypi:~/MagicMirror/modules/default/compliments $ pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/home/pi/.pm2/pm2.log last 15 lines:
PM2        | 2019-01-07T13:33:06: PM2 log: App [omx_stream1:1] starting in -fork mode-
PM2        | 2019-01-07T13:33:06: PM2 log: App [omx_stream1:1] online
PM2        | 2019-01-07T13:53:22: PM2 log: Stopping app:MagicMirror id:0
PM2        | 2019-01-07T13:53:23: PM2 log: pid=3567 msg=failed to kill - retrying in 100ms
PM2        | 2019-01-07T13:53:23: PM2 log: App [MagicMirror:0] exited with code [0] via signal [SIGINT]
PM2        | 2019-01-07T13:53:23: PM2 log: pid=3567 msg=process killed
PM2        | 2019-01-07T13:53:23: PM2 log: App [MagicMirror:0] starting in -fork mode-
PM2        | 2019-01-07T13:53:23: PM2 log: App [MagicMirror:0] online
PM2        | 2019-01-07T13:53:36: PM2 log: Stopping app:omx_stream1 id:1
PM2        | 2019-01-07T13:53:36: PM2 log: pid=3723 msg=failed to kill - retrying in 100ms
PM2        | 2019-01-07T13:53:36: PM2 log: pid=3723 msg=failed to kill - retrying in 100ms
PM2        | 2019-01-07T13:53:36: PM2 log: App [omx_stream1:1] exited with code [1] via signal [SIGINT]
PM2        | 2019-01-07T13:53:36: PM2 log: pid=3723 msg=process killed
PM2        | 2019-01-07T13:53:45: PM2 log: App [omx_stream1:1] starting in -fork mode-
PM2        | 2019-01-07T13:53:45: PM2 log: App [omx_stream1:1] online

/home/pi/.pm2/logs/omx-stream1-error.log last 15 lines:
1|omx_stre | /usr/bin/omxplayer: line 67: 15213 Aborted                 (core dumped) LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"
1|omx_stre | * failed to add service - already in use?
1|omx_stre | /usr/bin/omxplayer: line 67: 15247 Aborted                 (core dumped) LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"
1|omx_stre | * failed to add service - already in use?
1|omx_stre | /usr/bin/omxplayer: line 67: 15281 Aborted                 (core dumped) LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"
1|omx_stre | * failed to add service - already in use?
1|omx_stre | /usr/bin/omxplayer: line 67: 15315 Aborted                 (core dumped) LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"
1|omx_stre | * failed to add service - already in use?
1|omx_stre | /usr/bin/omxplayer: line 67: 15355 Aborted                 (core dumped) LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"
1|omx_stre | * failed to add service - already in use?
1|omx_stre | /usr/bin/omxplayer: line 67: 15409 Aborted                 (core dumped) LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"
1|omx_stre | * failed to add service - already in use?
1|omx_stre | /usr/bin/omxplayer: line 67: 15446 Aborted                 (core dumped) LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"
1|omx_stre | * failed to add service - already in use?
1|omx_stre | /usr/bin/omxplayer: line 67: 15496 Aborted                 (core dumped) LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"

/home/pi/.pm2/logs/MagicMirror-error.log last 15 lines:
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|MagicMir | [13988:0106/195336.292097:FATAL:bus.cc(1151)] D-Bus connection was disconnected. Aborting.
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|MagicMir | [1018:0107/114131.250034:FATAL:bus.cc(1151)] D-Bus connection was disconnected. Aborting.
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.



```

**Trying to restart via pm2 MagicMirror restart, MM does not restart:**

`[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/home/pi/.pm2/pm2.log last 15 lines:
PM2        | 2019-01-08T16:45:00: PM2 log: pid=6951 msg=failed to kill - retrying in 100ms
PM2        | 2019-01-08T16:45:00: PM2 log: pid=6951 msg=failed to kill - retrying in 100ms
PM2        | 2019-01-08T16:45:00: PM2 log: pid=6951 msg=failed to kill - retrying in 100ms
PM2        | 2019-01-08T16:45:00: PM2 log: pid=6951 msg=failed to kill - retrying in 100ms
PM2        | 2019-01-08T16:45:00: PM2 log: pid=6951 msg=failed to kill - retrying in 100ms
PM2        | 2019-01-08T16:45:00: PM2 log: pid=6951 msg=failed to kill - retrying in 100ms
PM2        | 2019-01-08T16:45:00: PM2 log: pid=6951 msg=failed to kill - retrying in 100ms
PM2        | 2019-01-08T16:45:00: PM2 log: pid=6951 msg=failed to kill - retrying in 100ms
PM2        | 2019-01-08T16:45:01: PM2 log: pid=6951 msg=failed to kill - retrying in 100ms
PM2        | 2019-01-08T16:45:01: PM2 log: pid=6951 msg=failed to kill - retrying in 100ms
PM2        | 2019-01-08T16:45:01: PM2 log: Process with pid 6951 still alive after 1600ms, sending it SIGKILL now...
PM2        | 2019-01-08T16:45:01: PM2 log: App [MagicMirror:0] exited with code [0] via signal [SIGKILL]
PM2        | 2019-01-08T16:45:01: PM2 log: pid=6951 msg=process killed
PM2        | 2019-01-08T16:45:01: PM2 log: App [MagicMirror:0] starting in -fork mode-
PM2        | 2019-01-08T16:45:01: PM2 log: App [MagicMirror:0] online

/home/pi/.pm2/logs/omx-stream1-error.log last 15 lines:
1|omx_stre | /usr/bin/omxplayer: line 67: 15213 Aborted                 (core dumped) LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"
1|omx_stre | * failed to add service - already in use?
1|omx_stre | /usr/bin/omxplayer: line 67: 15247 Aborted                 (core dumped) LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"
1|omx_stre | * failed to add service - already in use?
1|omx_stre | /usr/bin/omxplayer: line 67: 15281 Aborted                 (core dumped) LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"
1|omx_stre | * failed to add service - already in use?
1|omx_stre | /usr/bin/omxplayer: line 67: 15315 Aborted                 (core dumped) LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"
1|omx_stre | * failed to add service - already in use?
1|omx_stre | /usr/bin/omxplayer: line 67: 15355 Aborted                 (core dumped) LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"
1|omx_stre | * failed to add service - already in use?
1|omx_stre | /usr/bin/omxplayer: line 67: 15409 Aborted                 (core dumped) LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"
1|omx_stre | * failed to add service - already in use?
1|omx_stre | /usr/bin/omxplayer: line 67: 15446 Aborted                 (core dumped) LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"
1|omx_stre | * failed to add service - already in use?
1|omx_stre | /usr/bin/omxplayer: line 67: 15496 Aborted                 (core dumped) LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"

/home/pi/.pm2/logs/MagicMirror-error.log last 15 lines:
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|MagicMir | [13988:0106/195336.292097:FATAL:bus.cc(1151)] D-Bus connection was disconnected. Aborting.
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|MagicMir | [1018:0107/114131.250034:FATAL:bus.cc(1151)] D-Bus connection was disconnected. Aborting.
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.

**Comment by shbatm** [comment]
It appears you have the OpenGL drivers enabled -- OMXPlayer is not working with the OpenGL driver enabled on the newest version of Raspbian.  You'll need to switch to VLC or switch to the Legacy driver until they resolve this issue.

Closing this since it is not associated with this module in particular.
