### ISSUE TITLE
MagicMirror freezing with errors

### ISSUE THREAD

**Issue by anthony6608** [shbatm/MMM-RTSPStream#37]
Hey,

Sorry to bother you again. I made sure I switched to Legacy drivers after your last response:

> It appears you have the OpenGL drivers enabled -- OMXPlayer is not working with the OpenGL driver enabled on the newest version of Raspbian. You'll need to switch to VLC or switch to the Legacy driver until they resolve this issue.

However, the magicmirror is still locking up within an hour of me restarting. I can't even pm2 restart, I still have access to SSH but magicmirror wont restart at all. Its just stuck on the MM layout with time, video, date, etc frozen.  PM2 logs shows the following:

> `pi@raspberrypi:~/MagicMirror/modules/MMM-RTSPStream $ pm2 logs
> [TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
> /home/pi/.pm2/pm2.log last 15 lines:
> PM2        | 2019-01-11T16:39:06: PM2 log: Current arch         : arm
> PM2        | 2019-01-11T16:39:06: PM2 log: PM2 home             : /home/pi/.pm2
> PM2        | 2019-01-11T16:39:06: PM2 log: PM2 PID file         : /home/pi/.pm2/pm2.pid
> PM2        | 2019-01-11T16:39:06: PM2 log: RPC socket file      : /home/pi/.pm2/rpc.sock
> PM2        | 2019-01-11T16:39:06: PM2 log: BUS socket file      : /home/pi/.pm2/pub.sock
> PM2        | 2019-01-11T16:39:06: PM2 log: Application log path : /home/pi/.pm2/logs
> PM2        | 2019-01-11T16:39:06: PM2 log: Process dump file    : /home/pi/.pm2/dump.pm2
> PM2        | 2019-01-11T16:39:06: PM2 log: Concurrent actions   : 2
> PM2        | 2019-01-11T16:39:06: PM2 log: SIGTERM timeout      : 1600
> PM2        | 2019-01-11T16:39:06: PM2 log: ===============================================================================
> PM2        | 2019-01-11T16:39:06: PM2 log: [Watch] Start watching MagicMirror
> PM2        | 2019-01-11T16:39:06: PM2 log: App [MagicMirror:0] starting in -fork mode-
> PM2        | 2019-01-11T16:39:06: PM2 log: App [MagicMirror:0] online
> PM2        | 2019-01-11T16:40:41: PM2 log: App [omx_stream1:1] starting in -fork mode-
> PM2        | 2019-01-11T16:40:41: PM2 log: App [omx_stream1:1] online
> 
> /home/pi/.pm2/logs/omx-stream1-error.log last 15 lines:
> 1|omx_stre | /usr/bin/omxplayer: line 67: 15213 Aborted                 (core dumped) LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"
> 1|omx_stre | * failed to add service - already in use?
> 1|omx_stre | /usr/bin/omxplayer: line 67: 15247 Aborted                 (core dumped) LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"
> 1|omx_stre | * failed to add service - already in use?
> 1|omx_stre | /usr/bin/omxplayer: line 67: 15281 Aborted                 (core dumped) LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"
> 1|omx_stre | * failed to add service - already in use?
> 1|omx_stre | /usr/bin/omxplayer: line 67: 15315 Aborted                 (core dumped) LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"
> 1|omx_stre | * failed to add service - already in use?
> 1|omx_stre | /usr/bin/omxplayer: line 67: 15355 Aborted                 (core dumped) LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"
> 1|omx_stre | * failed to add service - already in use?
> 1|omx_stre | /usr/bin/omxplayer: line 67: 15409 Aborted                 (core dumped) LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"
> 1|omx_stre | * failed to add service - already in use?
> 1|omx_stre | /usr/bin/omxplayer: line 67: 15446 Aborted                 (core dumped) LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"
> 1|omx_stre | * failed to add service - already in use?
> 1|omx_stre | /usr/bin/omxplayer: line 67: 15496 Aborted                 (core dumped) LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"
> 
> /home/pi/.pm2/logs/MagicMirror-error.log last 15 lines:
> 0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
> 0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
> 0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
> 0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
> 0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
> 0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
> 0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
> 0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
> 0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
> 0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
> 0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
> 0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
> 0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
> 0|MagicMir | [926:0111/163854.258245:FATAL:bus.cc(1151)] D-Bus connection was disconnected. Aborting.
> 0|MagicMir | ATTENTION: default value of option force_s3tc_enable overridden by environment.
> `

**Comment by shbatm** [comment]
Not sure on that one... time for Google or the forums.

Also, I pushed another update to allow you to use omxplayer with OpenGL Fake KMS enabled.

**Comment by anthony6608** [comment]
Sorry was extremely busy for the past week or so. Just left everything as it was. I did unplug/replug a few times and had the same issue, coming back to a frozen MM. I could always access via SSH but it just seemed the MagicMirror was frozen on the screen. 

I just thought to ask you about my camera resolution as I saw you mention in another post that the Pi chokes on anything over 1080p. My camera is a 4mp Dahua camera and I had the resolution set to the max (2560x1440). Do you think that could be the problem? If this was in fact the culprit, wouldn't the entire Raspberry PI lock up and not allow me into SSH? In my case its just magic mirror freezing and it wont even restart via SSH. Either way I dropped the resolution down to 1920x1080p just in case. Also, this is a fresh install.  Curious to hear your thoughts on this. Thanks again for all of your help.

**Comment by anthony6608** [comment]
Also, I switched to FAKE KMS and rebooted, now the MagicMirror is flickering. I don't know what is going on here but I followed every instruction step by step and tried all your suggestions :( Im switching back to legacy for now.

**Comment by shbatm** [comment]
I would definitely try the lower resolution stream. The Pi doesn't like to
downsample video so see if your camera offers a lower resolution sub-stream
and if so, set the resolution close to the size of the window on your
mirror.

Regarding the flickering, search the forum, I thought I saw something on
there about it.

**Comment by JoJ123** [comment]
@anthony6608 @shbatm 
I'm facing the same issues. 
After 10-15 min MM freeze and then after 10 more minutes the whole Raspberry, just a hard boot is helping.

Do I have to setup up something special on the Raspi? I've used the installer script for MMM-RTPS?

My configuration:{
	module: "MMM-RTSPStream",
	position: "middle_center",
	header: "ARD",
		config: {
		autoStart: true,
		rotateStreams: false,
		rotateStreamTimeout: 10,
		moduleWidth: 354,
		moduleHeight: 240,
		localPlayer: 'vlc',
		remotePlayer: 'none',
		showSnapWhenPaused: false,
		remoteSnaps: false,
		shutdownDelay: 12,
			stream1: {
			name: 'RTL',
			url: 'rtsp://****************',
			frameRate: 'undefined',
			width: undefined,
			height: undefined,
			},
		}
}

**Comment by smartthinks** [comment]
@JoJ123

I have exactly the same problem.
I also have the "problem" that when I want to change things in the setup, de frame/stream of the camera stays in front of everything. So I cannot see the text behind it. 


module: "MMM-RTSPStream",
position: "bottom_center",
config: {
autoStart: true,
rotateStreams: false,
rotateStreamTimeout: 10,
moduleWidth: 468,
moduleHeight: 320,
localPlayer: 'omxplayer',
remotePlayer: 'none',
showSnapWhenPaused: false,
remoteSnaps: false,
moduleOffset: { left: -135, top: -165 },
stream1: {
name: 'Garage Botter Acker',
url: 'rtsp://User:Pass@***.***.***.***:554/cam/realmonitor?channel=1&subtype=1',
frameRate: undefined,
width: undefined,
height: undefined,
muted: true,
},
}
},
