### ISSUE TITLE
Connection Problem

### ISSUE THREAD

**Issue by ColdAcid7** [shbatm/MMM-RTSPStream#39]
H there,

I am having difficulties connecting to my IP-Cam.

The test-stream does work, the adress functions in VLC on Win10, but not on Raspi and therefore the video-section stays blank.

Here my config:
{
    module: "MMM-RTSPStream",
    position: "middle_center",
    config: {
        autoStart: true,
        rotateStreams: true,
        rotateStreamTimeout: 10,
        moduleWidth: 354,
        moduleHeight: 240,
        localPlayer: 'omxplayer',
        remotePlayer: 'none',
        showSnapWhenPaused: true,
        remoteSnaps: false,
        stream1: {
            name: 'GartenCAM',
            url: 'rtsp://xxx:yyy@192.168.178.48:554/live/ch0',
            frameRate: 'undefined',
            snapshotType: 'url',
            snapshotRefresh: 10,
            width: 354,
            height: 240,
            },
        }
},

I tried several different configs and URL's and can't figure out why the above URL works in Win, but not on Raspi VLC.

Thanks in advance for your support and best regards,
Stephan

**Comment by shbatm** [comment]
Is it a high resolution feed by any chance? The Pi tends to choke on anything over 1080p.

**Comment by ColdAcid7** [comment]
It is a 1080p feed that I only can change to 480p, which is too less to work with.

**Comment by ColdAcid7** [comment]
Since the first cam didn't offer a 2nd stream and had some other issues that couldn't be fixed, I changed to another camera, that offers a high- and low-rest stream. Both do work via VLC on a Win10 system, but neither does work on VLC on Raspi or MM. I am really lost now...

**Comment by ColdAcid7** [comment]
On another Raspi the high-res feed runs without any problems on Libreelec...

Is maybe any code missing?

**Comment by ColdAcid7** [comment]
Yes, latest Raspbian is installed, OpenGL (Fake KMS) enabled and tried 128 and 256 GPU/CPU split. I tried with omxplayer and ffmpeg, but neither connects with the stream - the same with VLC.
The raspi is connected to the network and internet. I can access it from a Win10 system with Putty and it imports data for other moduls via internet. The test.strm file I created does work on VLC Win10 and two other Raspberrys with LibreElec.
For me it seems that there is either a codec-problem or a connection-problem - both I can not understand.
Hope you have any ideas...

**Comment by ColdAcid7** [comment]
I was able to get VLC to stream both high- & low-res stream by simply using wired network, but still no success with getting the stream working within the module. Still don't get why VLC won't play the stream via wifi, since cam, router and raspi are within 2m range of each other and LibreElec-raspis play stream from way farther away via wifi.
