### ISSUE TITLE
Grey Screen - Default or any video not playing

### ISSUE THREAD

**Issue by iiMc204** [shbatm/MMM-RTSPStream#4]
Hello, I have followed the instructions and have done the solutions on the other closed issues. I am still having trouble with the screen box not showing anything at all. This is the MM Error log output:

> ffmpeg version 3.1.1 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.9.2 (Raspbian 4.9.2-10)
  configuration: --prefix=/usr --enable-gpl --enable-libx264 --enable-nonfree --enable-shared --disable-static
  libavutil      55. 28.100 / 55. 28.100
  libavcodec     57. 48.101 / 57. 48.101
  libavformat    57. 41.100 / 57. 41.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 47.100 /  6. 47.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
[RTSP demuxer @ 0x114d9e0] [Eval @ 0x7eb0ea4c] Undefined constant or missing '(' in 'undefined'
[RTSP demuxer @ 0x114d9e0] Unable to parse option value "undefined"
[RTSP demuxer @ 0x114d9e0] Error setting option rtsp_transport to value undefined.
rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov: Invalid argument

Thanks in advance.

**Comment by shbatm** [comment]
@iiMc204, please run the following and confirm the change fixed the problem.  There was a bug introduced in the latest version.

```
cd ~/MagicMirror/modules/MMM-RTSPStream
git pull
npm run-script update
```

**Comment by iiMc204** [comment]
Issue is fixed. Thanks so much!
