### ISSUE TITLE
does it could work on a docker installation?

### ISSUE THREAD

**Issue by todely** [shbatm/MMM-RTSPStream#48]
hello,

I run magicmirror serveronly with a docker and it seems RSTPStream module can't work inside docker ?

Thanks

**Comment by todely** [comment]
{ Error: spawn ffmpeg ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn ffmpeg',
  path: 'ffmpeg',
  spawnargs:
   [ '-rtsp_transport',
     'tcp',
     '-r',
     '30',
     '-i',
     'rtsp://adress_of_my_rtsp_stream',
     '-f',
     'mpegts',
     '-codec:v',
     'mpeg1video',
     '-an',
     '-bf',
     '0',
     '-' ] }

**Comment by dersch81** [comment]
I have it working with docker without any issues.

**Comment by todely** [comment]
I have delete all and restart a new container with same error..

**Comment by todely** [comment]
I have try to add -e package ffmpeg when create container but same error
ffmpeg is well installed on real env but it’s a more recent version than the one on readme
7:3.2.12-1~deb9u1+rpt1

**Comment by desq42** [comment]
@dersch81 
Would you mind, sharing your conf, My docker-Installation runs, but my Pi3-Magicmirror-Installation, just show "…loading…".

**Comment by dersch81** [comment]
Unfortunately it doesn't work anymore with the latest update. I also just used snapshots and not ffmpeg.
