### ISSUE TITLE
npm installation failed

### ISSUE THREAD

**Issue by sainiaj** [shbatm/MMM-RTSPStream#5]
Hi Thank you for making RTSP module really looking forward towards using this !!!!

I am unable to run the cmd npm install and gives me the following error code 

npm ERR! Linux 4.4.34-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! file /home/pi/MagicMirror/modules/MMM-RTSPStream/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Trailing comma in object at 21:1
npm ERR! }
npm ERR! ^
npm ERR! File: /home/pi/MagicMirror/modules/MMM-RTSPStream/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/MagicMirror/modules/MMM-RTSPStream/npm-deb

**Comment by iiMc204** [comment]
Hello, I had the same issue last night and I was able to go through the installation by editing package.json by removing a comma. Edit your package.json file and delete the last comma and try npm install again.

**Comment by shbatm** [comment]
Fixed the typo.  Must have missed the comma when I was pulling out some unnecessary info in the package.json file. That's what I get for trying to clean!
