### ISSUE TITLE
[Bug] omx_stream1 stopped

### ISSUE THREAD

**Issue by buzzkc** [shbatm/MMM-RTSPStream#52]
I'm using the MMM-Remote-control module to toggle the screen on and off, I'm running the development branch using the omxplayer. Video is working, but when the monitor is toggled off the pm2 omx_stream1 task stops, when toggling the monitor back on, the MMM-Remote-control module sends the User-Presence notification with a payload of true, but the playAll function doesnt seem to do anything, the omx_stream1 task remains stopped, I can manually restart the omx_stream1 task and video resumes at that point.

**Comment by buzzkc** [comment]
I'll work more on debugging this over the next few nights. I went through the stack to see where it may not be re-starting the pm2 omx_stream1 task and added some comments of places to check...
`
https://github.com/Jopyth/MMM-Remote-Control/blob/master/node_helper.js:617

		this.sendSocketNotification("USER_PRESENCE", true);



https://github.com/shbatm/MMM-RTSPStream/blob/master/MMM-RTSPStream.js:489

		if (notification === "USER_PRESENCE") {
            if (payload) {
                this.resume(); // <<<
            } else {
                this.suspend();
            }
        }
        
        
https://github.com/shbatm/MMM-RTSPStream/blob/master/MMM-RTSPStream.js:160
	resume: function() {
        console.log(`${this.name} has resumed...`);
        this.suspended = false;
        if (this.loaded) { //? Set to true by STARTED notification and that it's not already true.
            if (this.config.rotateStreams) {
                this.setupStreamRotation();
            } else if (this.config.autoStart) {
                this.playAll(); //if loaded true, this should get called
            } else {
                Object.keys(this.streams).forEach(s => this.playSnapshots(s));
            }
        }
    },
    
    
https://github.com/shbatm/MMM-RTSPStream/blob/master/MMM-RTSPStream.js:388
    playAll: function() {
        var ps = [];
        Object.keys(this.streams).forEach(s => {
            if (this.kbInstance === "SERVER" || (this.kbInstance === "LOCAL" && this.config.remotePlayer === "ffmpeg")) { //? Not sure of kbInstance value, if neither, then PLAY_OMXSTREAM never gets called
                var res = this.playStream(s);
                if (res.length > 0) {
                    ps = ps.concat(res);
                }
                if (!(this.kbInstance === "SERVER" && this.config.remoteSnaps)) {
                    this.sendSocketNotification("SNAPSHOT_STOP", s);
                }
            }
        });
        if (ps.length > 0) { this.sendSocketNotification("PLAY_OMXSTREAM", ps); }
    },
    
    
https://github.com/shbatm/MMM-RTSPStream/blob/master/node_helper.js:272
        if (notification === "PLAY_OMXSTREAM") {
            this.getOmxplayer(payload);
        }


https://github.com/shbatm/MMM-RTSPStream/blob/master/node_helper.js:90
    getOmxplayer: function(payload) {
        var self = this;
        var opts = { detached: false, stdio: 'ignore' };

        var omxCmd = `omxplayer`;

        var namesM = [];

        var argsM = [];

        payload.forEach(s => {
            var args = ["--live", "--video_queue", "4", "--fps", "30",
                this.config[s.name].url
            ];
            if (!("fullscreen" in s)) {
                args.unshift("--win", `${s.box.left}, ${s.box.top}, ${s.box.right}, ${s.box.bottom}`);
            } else {
                if ("hdUrl" in this.config[s.name]) {
                    args.pop();
                    args.push(this.config[s.name].hdUrl);
                }
            }
            if (this.config[s.name].protocol !== "udp") {
                args.unshift("--avdict", "rtsp_transport:tcp");
            }
            console.log(`Starting stream ${s.name} with args: ${JSON.stringify(args,null,4)}`); //I see this output in pm2 log

            argsM.push(args);
            namesM.push("omx_" + s.name);
        });

        // this.omxStream[payload.name] = child_process.spawn(omxCmd, args, opts); //??

        // PM2 Test
        var pm2 = require('pm2');

        pm2.connect((err) => {
            if (err) {
                console.error(err);
                process.exit(2);
            }

            // Stops the Daemon if it's already started
            pm2.list((err, list) => {
                var errCB = (err, apps) => {
                    if (err) { console.log(err); }
                };

                var startProcs = () => { //Failing in here somewhere? This gets called after pm2.stop below
                    if (namesM.length > 0) {
                        console.log("Starting PM2 for " + namesM[namesM.length - 1]); //is this message in output?
                        pm2.start({
                            script: "omxplayer",
                            name: namesM[namesM.length - 1],
                            interpreter: 'bash',
                            out_file: "/dev/null",
                            //interpreterArgs: '-u',
                            args: argsM[namesM.length - 1],
                            //max_memory_restart : '100M'   // Optional: Restarts your app if it reaches 100Mo
                        }, (err, proc) => {
                            console.log("PM2 started for " + namesM[namesM.length - 1]);
                            this.omxStream[namesM[namesM.length - 1]] = namesM[namesM.length - 1];
                            namesM.pop();
                            argsM.pop();
                            startProcs();
                            if (err) { throw err; }
                        });
                    } else {
                        pm2.disconnect(); // Disconnects from PM2
                    }
                };

                for (var proc in list) {
                    if ("name" in list[proc] && namesM.indexOf(list[proc].name) > -1) {
                        if ("status" in list[proc].pm2_env && list[proc].pm2_env.status === "online") {
                            console.log(`PM2: ${list[proc].name} already running. Stopping old instance...`);
                            pm2.stop(list[proc].name, errCB);
                        }
                    }
                }

                startProcs();
            });

        });
    },
`

**Comment by buzzkc** [comment]
Running npm start dev, these are the messages when turning off the monitor, then back on manually

<turned monitor off here>
PM2: Stopping all OMXPlayer Streams...
PM2: Checking if omx_stream1 is running...
PM2: Stopping omx_stream1...
state 0xa [HDMI CEA (16) RGB lim 16:9], 1920x1080 @ 60.00Hz, progressive

<turned monitor on here>
Powering on HDMI with preferred settings

**Comment by buzzkc** [comment]
Solved...There is a typo on line 586 of MMM-RTSPsuspend.js

this.suspsended >>> this.suspended

**Comment by shbatm** [comment]
Good catch! This has been fixed in `develop`.  Sorry for the lack of responses, I've been busy with other projects.

**Comment by buzzkc** [comment]
No worries, thank you!
