### ISSUE TITLE
[Bug] No stream with VLC or OMXPlayer, FFMpeg works - random errors in Log

### ISSUE THREAD

**Issue by BKeyport** [shbatm/MMM-RTSPStream#55]
**Describe the bug**
unable to get picture/stream from VLC or OMXPlayer on master branch. While debugging other module, I noticed a whole bunch of errors in log. 

**To Reproduce**
Run MagicMirror with RTSP-Stream configured. 

**Expected behavior**
Stream from Camera. 

**Configuration**
		{
			module: "MMM-RTSPStream",
			position: "top_right",
			config: {
				autoStart: true,
				rotateStreams: false,
				moduleWidth: 640,
				moduleHeight: 360,
				localPlayer: 'omxplayer', // Or localPlayer: 'vlc',
				remotePlayer: 'ffmpeg',
				showSnapWhenPaused: false,
				remoteSnaps: false,
				omxRestart: 2,
				stream1: {
					name: 'Front Camera',
					url: 'rtsp://user:pass@address/h264Preview_01_main', // Edited for privacy
					protocal: "ucp",
					width: 640,
					height: 360, 
					ffmpegPort: 10002,
					shutdownDelay: 0,
					muted: true,
				},
			}
		},

**Logs**
0|mm     | TypeError: Cannot convert undefined or null to object
0|mm     |     at Function.keys (<anonymous>)
0|mm     |     at stopProcs (/home/pi/MagicMirror/modules/MMM-RTSPStream/node_helper.js:469:32)
0|mm     |     at pm2.list (/home/pi/MagicMirror/modules/MMM-RTSPStream/node_helper.js:498:17)
0|mm     |     at /home/pi/MagicMirror/modules/MMM-RTSPStream/node_modules/pm2/lib/API.js:606:19
0|mm     |     at /home/pi/MagicMirror/modules/MMM-RTSPStream/node_modules/pm2-axon-rpc/lib/client.js:45:10
0|mm     |     at Parser.<anonymous> (/home/pi/MagicMirror/modules/MMM-RTSPStream/node_modules/pm2-axon/lib/sockets/req.js:67:8)
0|mm     |     at Parser.emit (events.js:182:13)
0|mm     |     at Parser._write (/home/pi/MagicMirror/modules/MMM-RTSPStream/node_modules/amp/lib/stream.js:91:16)
0|mm     |     at doWrite (_stream_writable.js:410:12)
0|mm     |     at writeOrBuffer (_stream_writable.js:394:5)
**Additional context**

If you are not comfortable posting the logs or configuration on a public place, you may also send @shbatm a private chat on the [MagicMirror² Forum](https://forum.magicmirror.builders) or send an e-mail to support@shbatm.com.  E-mails asking general questions or without an accompanying Issue will not be answered.

**Comment by tanvir586** [comment]
Same to me

**Comment by BKeyport** [comment]
FYI, I got OMX working on develop branch, does not work on master - capitalization issue on URL fixed that.

**Comment by BKeyport** [comment]
More info: 

VLC won’t work.

Syntax error on command line, so it’s trying to load local file “dummy” rather than stream. I can fix this by removing the word “dummy” in node_helper.js, along with it’s quotes and comma.

There’s a problem with the way that VLC is called by node (the system behind magic mirror) that is blocking the video stream from flowing. If I remove the “-I” from the arguments, I can get a VLC box that runs, and when I check the stream stats, the audio is flowing freely, but the video is stuck. 

Would it be possible to try and launch a Pm2 object like OMX?

**Comment by Biostim** [comment]
Guys, I've managed to get VLC working.
It seems that the getVlcPlayer function was not being called:
if (notification === "PLAY_VLCSTREAM") {
	this.getVlcPlayer(payload);
}

Just replace "this" with "self".

Unfortunately, the window just shows up in the top left corner, not where it's supposed to appear.
I won't be spending more time with this module because I'm building my mirror with an old machine and the mirror with this module uses 70% of the CPU. Not something I want.
Anyway, shouldn't be too hard to have it properly displayed. Just play around with wmctrl, vlc and devilspie2 options.

**Comment by BKeyport** [comment]
I *think* the bit called DP2 (Devil's Pie 2?) is supposed to move the window where it belongs. Not sure tho - it's only used when VLC is supposed to be in use.

**Comment by BKeyport** [comment]
I've given up as well, I'm actively searching for ways to get rid of the module totally.
