### ISSUE TITLE
My config not show up

### ISSUE THREAD

**Issue by Dylantje** [shbatm/MMM-RTSPStream#58]
Hope there is...

http://192.168.5.233:7777/MMM-RTSPStream/config.html

Not showing anything
And in my module stay this adres to open... for config

So hope there is someone

**Comment by stampeder** [comment]
I have the same problem. Followed all the installation process as described. My browser never finds the config.html page.

**Comment by edogbert** [comment]
I ran into the same issue and I needed to adjust the top of the config.js file as such. Not sure if it will help but it did it for me.

var config = {
        address: "0.0.0.0",
        port: 8080,
        ipWhitelist: [], // Set [] to allow all IP addresses

**Comment by kniferider** [comment]
Change of config.js was successful for me, but now I get:
Cannot GET /MMM-RTSPStream/public/config.html

???
