### ISSUE TITLE
[Bug] Dependency issues on new install.

### ISSUE THREAD

**Issue by stampeder** [shbatm/MMM-RTSPStream#59]
Got as brand new install of MagicMirror2 with all the latest dependencies loaded. When I tried to install MMM-RTSPStream in my MagicMirror directory I got this list of deprecated and missing dependencies:
npm WARN lifecycle MMM-RTSPStream@2.0.2-dev~preinstall: cannot run in wd MMM-RTSPStream@2.0.2-dev ./scripts/preinstall.sh (wd=/home/pi/MagicMirror/modules/MMM-RTSPStream)
npm WARN deprecated datauri@1.1.0: Datauri 2.0 released. See more in https://github.com/data-uri/datauri/releases/tag/v2.0.0
npm WARN deprecated mimer@0.3.2: Mimer 1.0 released. See more in https://github.com/data-uri/mimer/releases/tag/v1.0.0
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q git://github.com/shbatm/node-rtsp-stream-es6.git /root/.npm/_cacache/tmp/git-clone-72d02314/.git
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-72d02314/.git'
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-24T20_43_02_693Z-debug.log
Failed to install dependencies.
Can someone help with a solution? I would really like to use this with my cameras on ffmpeg.
Thanks.

**Comment by codingwatermelon** [comment]
Just wanted to say that I'm getting the same error and not sure what to do.
