### ISSUE TITLE
Websocket exception

### ISSUE THREAD

**Issue by kaumi345** [shbatm/MMM-RTSPStream#6]
I have configured the URL in Config.js
like this 

url: 'resp://192.168.1.22',

So at start i get the following error.
I Hope you could help me.
Greets kaumi 

![image](https://user-images.githubusercontent.com/13404419/28220717-d6c59b74-68c0-11e7-968c-941908b5d254.jpg)

**Comment by shbatm** [comment]
@kaumi345 -- Looks like its an issue with the port.  

You have `port: 554' which is the default RTSP port, but the `port` setting in the module config is for the module's internal websocket, not the video stream URL. 

It has to be 1) unique, 2) available (nothing else using that port) and 3) higher than 1024 if you're not running the MM under sudo.  I would leave it as `port: 9999` if you're only running 1 camera.

For the camera's port, just add it to the end of the url: 
```shell
url: 'rtsp://192.168.1.22:554',
```

**Comment by kaumi345** [comment]
Thx, it's working for me
