### ISSUE TITLE
2 Amcrest Cameras, only one works

### ISSUE THREAD

**Issue by mitch1138** [shbatm/MMM-RTSPStream#66]
I am unable to display Amcrest cameras in MM using http.  Using MMM-RTSPStream with only the camera address changed, one camera will display (IPM3-943W) and one will not (empty box, IPM4-1026P).  Both will display as rtsp in VLC on windows and using motioneye on the Raspberry Pi.  Any suggestions on what I might be doing wrong. Using:  url: 'rtsp://user:password@IP:Port/cam/realmonitor?channel=1&subtype=0'
Many thanks, Dave

**Comment by tung256** [comment]
did you solve this?

**Comment by mitch1138** [comment]
Sorry, No.
