### ISSUE TITLE
blank display

### ISSUE THREAD

**Issue by shadownomore** [shbatm/MMM-RTSPStream#7]
for some reason i cant get the stream to display. Mine or the default one. Ive tested both in VLC and they both work. checked and everything is up to date. any help you can give would be greatly appreciated. thanks

**Comment by shbatm** [comment]
Please provide a copy of the module config that you used.  Also, have you confirmed ffmpeg has been installed and have run `npm install` inside the module's directory?

**Comment by shadownomore** [comment]
`{
            module: 'MMM-RTSPStream',
            position: 'middle_center',
            config: {
                autoStart: true,
                rotateStreams: false,
                rotateStreamTimeout: 10,
                showSnapWhenPaused: false,
                moduleWidth: 354,
                moduleHeight: 240,
                player: 'omx',
                stream1: {
                    name: 'Front Door',
                    url: 'http://192.168.1.177:65520/videostream.asf?user=user&pwd=password&resolution=64&rate=0',
                    snapshotUrl: '',
                    snapshotRefresh: 10, // Seconds
                    frameRate: "30",
                    port: 9999,
                }
            }
        },`

above is the config that im using. Ive got it now to where the default stream will work but when i change it to mine i just get a gray box in the middle of the screen, even though the feed works in VLC.

**Comment by shbatm** [comment]
Unfortunately I not yet tested this with an `http://` protocol.  It's on my TO-DO list, but I don't have one to test with.  What model camera are you trying to connect to?

1) You can try adding `protocol: "udp",` in the stream1 config section.
2) Are you getting any errors in the console / pm2 logs? Add `hideFfmpegOutput: false` after `port: 9999,` to get the `ffmpeg` errors to appear in the MM2 logs
3) Can you access the stream directly using a webpage? Have you confirmed if you need a plugin to play the video?  If no plugin is required, you could try and use the MMM-iFrame module for now until I add direct streaming capabilities to the module.
4) You can try playing with the `ffmpeg` command line arguments yourself and see if you get any errors.  The default is:
```shell
ffmpeg -rtsp_transport tcp -r 30 -i {{YOUR URL}} -f mpegts -codec:v mpeg1video -bf 0 -
```
5) If you're willing to do some experimentation you can install the `dev` branch which uses `omxplayer` for the local screen (no video will be accessible from a browser on another computer, but it uses the GPU so it will run much faster).  More details in [this thread](https://forum.magicmirror.builders/topic/2743/mmm-rtspstream-video-streaming-from-live-feeds-security-cameras/9?page=1).  To
```shell
    cd ~/MagicMirror/modules/MMM-RTSPStream
    git checkout wip
    # Update node modules
    npm run-script update
```

**Comment by psteimann** [comment]
I have the same problem (blank window in position middle_enter) but with rtsp. The stram works (see config), tested with Ispy and VLC. So Portforwarding, Firewall etc must be ok
Here is my config:
config: {
                	autoStart: true,
                	rotateStreams: false,
                	rotateStreamTimeout: 10,
                	showSnapWhenPaused: false,
                	moduleWidth: 354,
                	moduleHeight: 240,
                	stream1: {
                    	name: 'DLinkStream',
                    	url: 'rtsp://xxxx:yyyy@85.4.235.67:554/play1.sdp',
			snapshotUrl: '',
                    	snapshotRefresh: 0, // Seconds
                    	frameRate: "30",
                    	port: 9999,
               		 	}
            		}

**Comment by psteimann** [comment]
Solved the problem now: I had to change the port from 8088 to 8099...

**Comment by marcelontime** [comment]
@psteimann which port? I'm having the same issue...

**Comment by psteimann** [comment]
The Port in the config.js on the top of the file.
