### ISSUE TITLE
boarder issue 

### ISSUE THREAD

**Issue by 4-sherad** [shbatm/MMM-RTSPStream#72]
Hi there, 

i was hoping you could tell me how to get rid of the white boarder that is around the camera feed, don't know if it should be but on my screen the boarder is bigger than the camera feed its self and its annoying to look at, i have tried changing the width and height of the camera but the boarder just's gets bigger with it.any help is most appreciated.

Thanks, Adam

**Comment by nodashipl** [comment]
I would like to do this too. The video doesnt align with the boarder and i wish i could remove the white boarder otherwise everything else works great
