### ISSUE TITLE
[Bug] After a random couple of ours the stream stops by itself.

### ISSUE THREAD

**Issue by smartthinks** [shbatm/MMM-RTSPStream#73]
Hello,

I have build a 2 magic mirror with a raspberryPI4 4gb. 
We use the stream, and after a random couple of ours the stream freezes. 
I’ve build 2 mirrors with the same module, 1 on WiFi and 1 on lan-cable connection, and both streams stop at different times. 
So thats why I dont think that the issues came from the recorder (NVR) 
But I can’t find out what would go wrong with the script, Im using the VLC player.
The stream is running very good.
Is there maybe an option for rebooting when the frame freezes automaticly. Or is there someone who had the same issues, and have the solution for me. 

Thanks Greetings Jerry from Holland

**Comment by smartthinks** [comment]
{
module: "MMM-RTSPStream",
position: "bottom_center",
config: {
autoStart: true,
rotateStreams: false,
rotateStreamTimeout: 20,
moduleWidth: 352,
moduleHeight: 242,
localPlayer: "vlc", // "omxplayer" or "ffmpeg", or "vlc"
remotePlayer: 'none',
showSnapWhenPaused: false,
remoteSnaps: false,
omxRestart: 2, //Hours
vlcRestart: 2, //Hours.     
stream1: {
name: 'Garage Botter Acker',
url: 'rtsp://user:wachtwoord@***.***.***:554/cam/realmonitor?channel=1&subtype=1',
  protocol: "udp", // 'tcp' or 'udp'
  frameRate: undefined, 
  width: 352,
  height: 242,
  muted: true,
},

**Comment by lacee82** [comment]
Any solution on this? I have the same issue. Stream freezing after random amount of time.
