### ISSUE TITLE
[Bug] RTSP stream is not displayed only a white border

### ISSUE THREAD

**Issue by HagridStav** [shbatm/MMM-RTSPStream#75]
This is my configuration:
{
			module: "MMM-RTSPStream",
			position: "middle_center",
			config: {
				autoStart: true,
				rotateStreams: false,
				rotateStreamTimeout: 10,
				moduleWidth: 354,
				moduleHeight: 240,
				localPlayer: 'omxplayer',
				remotePlayer: 'ffmpeg',
				showSnapWhenPaused: false,
				remoteSnaps: true,
				shutdownDelay: 12,
					stream1: {
					name: 'test',
					url: 'rtsp://192.168.x.x:554/user=admin&password=admin&channel=1&stream=1?.sdp',
					frameRate: 'undefined',
					width: undefined,
					height: undefined,
					ffmpegPort: 9999,
					},
				}
		},

The same RTSP stream works perfectly in VLC player on RPI 4 4GB.
I don't know what the problem is. Please help me.

**Comment by ingo916** [comment]
i ave the same issue where i get 4 white border squares. The rtsp stream works fine with vlc player.
I did notice that a clean build of MM with just the default config i get the streams to work. however when i and any module like MMM-CalendarEXT it only shows the rtsp module only displays the white border of the windows for the stream.

**Comment by codac** [comment]
I can confirm that issue for Wanview W2 cameras.

`                {
                        module: 'MMM-RTSPStream',
                        position: 'middle_center',
                        config: {
                                autoStart: true,
                                rotateStreams: true,
                                showSnapWhenPaused: false,
                                moduleWidth: 728,
                                moduleHeight: 240,
                                localPlayer: 'vlc',
                                stream1: {
                                        name: 'Cam1',
                                        url: 'rtsp://<username:pass>@<ip>/mpeg/media.amp',
                                        snapshotUrl: '',
                                        snapshotRefresh: 10, // Seconds
                                        frameRate: "10",
                                        port: 80,
                                },
                                stream2: {
                                        name: 'Cam2',
                                        url: 'rtsp://<username:pass>@<ip>:<port>/live/ch0',
                                        snapshotUrl: '',
                                        snapshotRefresh: 10, // Seconds
                                        frameRate: "30",
                                },
                                stream3: {
                                        name: 'Cam3',
                                        url: 'rtsp://<username:pass>@<ip>:<port>/live/ch0',
                                        snapshotUrl: '',
                                        snapshotRefresh: 10, // Seconds
                                        frameRate: "30",
                                },
                                stream4: {
                                        name: 'Cam4',
                                        url: 'rtsp://<username:pass>@<ip>:<port>/live/ch0',
                                        snapshotUrl: '',
                                        snapshotRefresh: 10, // Seconds
                                        frameRate: "30",
                                },
                        }
                },
`

**Comment by mnyqvist** [comment]
Same problem for me, get these errors
[17.06.2021 08:31.58.706] [LOG] Starting stream stream1 using VLC with args --width 352 --height 242 -I dummy --video-on-top --no-video-deco --no-embedded-video --video-title=stream1 http://admin:password@192.168.1.79/video.cgi…
[17.06.2021 08:31.58.728] [ERROR] Failed to start subprocess: [object Object].
[17.06.2021 08:31.58.751] [LOG] DP2: Config File Saved!
[17.06.2021 08:31.58.752] [INFO] DP2: Running window resizers…
[17.06.2021 08:31.58.768] [ERROR] DP2: Failed to start.
[17.06.2021 08:32.05.769] [INFO] DP2: Running window resizers…
[17.06.2021 08:32.05.779] [ERROR] DP2: Failed to start.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! magicmirror@2.15.0 start: electron js/electron.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the magicmirror@2.15.0 start script.
