### ISSUE TITLE
[Bug] VLC Black Screen with PM2

### ISSUE THREAD

**Issue by snarlingllama** [shbatm/MMM-RTSPStream#76]
After upgrading to the latest version of MagicMirror and PM2, this module only shows a black screen for the VLC pop-up windows. Interestingly, when I run `npm start` everything works fine. It is only when I run `pm2 start mm` that the issue occurs. This was not an issue during the first 24hrs after the update. I greatly prefer to use pm2 on account of scheduling cron jobs to restart the mirror.

Is there a specific version of PM2 that I should downgrade to?

**Comment by NathTheDude** [comment]
Looks to still be an issue, works when I use 'npm start' but not with pm2 :-(

**Comment by CatoAntonsen** [comment]
Works fine here:
pi@mirror:~/MagicMirror $ pm2 -v
5.1.0

**Comment by wxflint** [comment]
Same issue here

**Comment by FuryGear** [comment]
Does this module not work with the latest version of MagicMirror anymore?
