### ISSUE TITLE
Module doesn't rotate on vertical Screen

### ISSUE THREAD

**Issue by miker2000** [shbatm/MMM-RTSPStream#80]
I have my Magic Mirror on a Vertical screen ( a matter of taste ) however the module doesn't seem to understand this.

A white square is showed where it is expected, the designated stream however is in a place where it would be is I have it horizontally and off course it is tilted

**Comment by websterjazz** [comment]
@shbatm I am facing a similar issue as @miker2000 
The orientation of the camera feed is different from my mirror orientation. Please check the attached image for refereference.

[https://ibb.co/t3qbC78]()
