### ISSUE TITLE
[Bug] MagicMirror not starting "Request" not found

### ISSUE THREAD

**Issue by Chr1sDub** [shbatm/MMM-RTSPStream#90]
hey there
i´ve got an issue with the module
please see logfile attached

thanks in advance

> [13.10.2021 22:52.46.287] [ERROR] [31mWARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'request'[39m
> 
> [31mRequire stack:[39m
> [31m- /home/pi/MagicMirror/modules/MMM-RTSPStream/node_helper.js[39m
> [31m- /home/pi/MagicMirror/js/app.js[39m
> [31m- /home/pi/MagicMirror/js/electron.js[39m
> [31m- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js[39m
> [31m- [39m
> [13.10.2021 22:52.46.303] [ERROR] App threw an error during load
> [13.10.2021 22:52.46.308] [ERROR] Error: Cannot find module 'request'
> Require stack:
> - /home/pi/MagicMirror/modules/MMM-RTSPStream/node_helper.js
> - /home/pi/MagicMirror/js/app.js
> - /home/pi/MagicMirror/js/electron.js
> - /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
> - 
>     at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
>     at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
>     at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
>     at Module._load (internal/modules/cjs/loader.js:732:27)
>     at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
>     at Module.require (internal/modules/cjs/loader.js:959:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
>     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-RTSPStream/node_helper.js:11:15)
>     at Module._compile (internal/modules/cjs/loader.js:1078:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
> [13.10.2021 22:52.46.310] [ERROR] Whoops! There was an uncaught exception...
> [13.10.2021 22:52.46.322] [ERROR] Error: Cannot find module 'request'
> Require stack:
> - /home/pi/MagicMirror/modules/MMM-RTSPStream/node_helper.js
> - /home/pi/MagicMirror/js/app.js
> - /home/pi/MagicMirror/js/electron.js
> - /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
> - 
>     at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
>     at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
>     at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
>     at Module._load (internal/modules/cjs/loader.js:732:27)
>     at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
>     at Module.require (internal/modules/cjs/loader.js:959:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
>     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-RTSPStream/node_helper.js:11:15)
>     at Module._compile (internal/modules/cjs/loader.js:1078:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/pi/MagicMirror/modules/MMM-RTSPStream/node_helper.js',
>     '/home/pi/MagicMirror/js/app.js',
>     '/home/pi/MagicMirror/js/electron.js',
>     '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
>     undefined
>   ]
> }
> [13.10.2021 22:52.46.324] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
> [13.10.2021 22:52.46.325] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
>

**Comment by shbatm** [comment]
closed with  b2d2710
